---
title: "STAT/DATA 234 Course Reflection"
format: 
  html:
    self-contained: true
---

The purpose of this 10 point course reflection is for you to reflect on what you've learned in this class throughout this semester. Answer each question in 2-3 complete sentences. Each question is worth 2 points. Note that, for parts b, c, d, and e, you may be asked to share what you wrote with another student.

a. (2 points) Tell me a thing or two that you've learned about yourself from taking this class. This might be a perceived strength, weakness to work on, or something else entirely!

b. (2 points) What was your favourite part or parts of learning data science or of this class. Why? (Even if you hated everything, choose "the best of the worst")

c. (2 points) What was your least favourite part or parts of learning data science or of this class? Why? (Even if you loved everything, choose "the worst of the best")

d. (2 points) Explain one way in which data science, or this class, was similar to what you thought it would be. Explain one way in which data science, or this class, was different than what you thought it would be. 
e. (2 points) What advice would you give someone taking this course in a future semester?

<br>
