---
title: "Student Advice (Fall 2021)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The following pieces of advice were submitted at the end of the semester by students taking this class in the Fall of 2021. The prompt for students was "What advice would you give someone taking this course next fall?" The advice given was not anonymous to me (this was part of a small graded assignment), but I have not edited any of their responses.

* Advice I would give for this class is to reference work you did in class when working on homework, quizzes, or projects. It can be very helpful especially if you are unsure where to start. Additionally, I think a very important piece of advice is to really try and complete the exercises without looking at the answers. It is good practice and can definitely be challenging but the next time when a similar question, you are able to look back and more actively remember how to approach the problem.

* Learn the basics from the beginning. It will pay off in the long run.

* My advice for someone taking this class next fall would be to not get discouraged and go to office hours. Also, it is best to attempt assignments as early as possible.

* Keep up with the course, if you don’t understand something try to sort it out so it doesn’t hurt you down the road. Ask questions and put in the effort!

* PAY ATTENTION! I think this class is really easy to fall behind in. Spend a good amount of time learning the first main functions because you’ll use them for the entire class. With that being said, if you’re confused at the beginning ask for help, because the new material will be added on to the old.

* This class is so much more about what you learn than the grade. If you want you can get a good grade with ease, but more importantly put in the effort to understand because the content is interesting and builds upon the prior work.

* Some advice I would give to someone taking this course next fall would be to study for the in-person quizzes because it helps for the quiz, and also helps you for future assignments. I would also advise someone taking this course to not procrastinate when it comes to the projects, and to start early rather than to leave the projects for the last minute.

* I would tell them to be patient. Data science does not always make sense immediately, rather some topics (dplyr specifcally) take many examples and practice. I would also tell them to use their resources, class notes, handouts, and quizzes to answer any questions. Also, I would tell them to keep an open mind, and not be hesitant to ask questions, as it is likely others will have the same question.

-------------------------------------------------
-------------------------------------------------

* I would say the best way to take notes is directly in R. When taking the notes you can organize them super well by labeling just like the code is labeled in the packet, so when you go back it is much easier to find the code. If you follow along with the packet and professor in class, then it should be fairly understandable. When you are working on projects don’t just get stumped on one line of code for an hour, either move on and go back or just ask the professor for help. Otherwise you may be there all day when it could be a very simple explanation you just haven’t seen yet. (Fresh eyes are always better, so stepping away for an hour or two could help a lot)

* I would tell them to work with other people in the class and just talk through problems together because together it would be a lot easier, especially if your code wasn’t working for some reason.

* I would suggest going back through the lecture code and typing the commands by hand after going through them in lecture, just to cement the code in your memory.

* Just practice tidyr and dplyr.

* Advice that i would give a future student is to actually do the exercises and keep from looking at the solutions. This will really help you learn the material and make you memorize it.

* Some advice I would have is just to stay on top of the work and ask questions if you don't understand something because the material does build on previous stuff so it is better to understand as you go rather than be lost down the road.

* Keep your files organized. It will pay off in the long run. Do this for other classes too.

* My advice would be to actively participate and follow along on your own R markdown in class. I feel that I was able to do well on the course becasue I was working through lectures on my own computer.

-------------------------------------------------
-------------------------------------------------

* My advice would be to stay on top of your work at all costs. Do not take a HW or a quiz lightly, it will help in the long run.

* I would tell them to stick with the material even though it may seem confusing at first. I struggled at the beginning, especially since I joined a few weeks late. However, most things ended up making sense as I got more practice with the code, and I ultimately enjoyed this class and data science, in general.

* I would tell any prospective intro data science students to get a little comfortable with R before taking the class, or at least some sort of computer program so you don’t struggle as much with the actual coding part and can focus more on the content of the course. Also, don’t stress too much at the beginning if you struggle with coding and understanding R because as you practice more and more you become more comfortable with it and will eventually be able to do some pretty cool things.

* Create a study group to work on projects and quizzes together. When you get stuck on something in R, it can be very frustrating but having another perspective and a helping hand is extremely useful!

* My advice does not just to remember every function; you need to understand the concepts. If you do not understand the materials, you will get messed up with those similar functions. It may be helpful that to help people to find a group to work together.

* Stay organized and everything becomes a lot easier.

* Get the most out of this class that you can. No matter what field you are going into I feel like some knowledge of how to analyze data and make graphs and tables is a good way to impress a boss or a good way to showcase your ideas and back them up.

* The biggest piece of advice I would give to a student taking this course next Fall would be to be patient, especially if this is your first computer science-y course. Don’t feel threatened by all the fancy R jargon used in error messages, as you can usually get to the root of the issue by running through the individual lines of code and changing just that one line.

