---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### STAT 234 Midpoint Feedback

Since we about a third of the way through the semester (Woohoo!), I would like to get your perspective about how this course is going so far. To do so, answer the following questions. You can write your name on this sheet if you want, or you can keep it anonymous.

1. On a scale from 1 to 5 (1 being not useful at all, 3 being somewhat useful, and 5 being very useful), rate the following components of the course as they relate to the usefulness of your learning:

a. Class time spent going through the course materials as a class.

b. Class time spent working on your own, with a partner, or with your group on the Exercises.

c. Exercises that you complete and turn in on your own (that are due on Mondays).

d. Completing the take-home portion of the quizzes.

e. Completing the first project.

&nbsp;

2. Rate your comfort level with `R Studio` and computer programming in general at the beginning of the course (1 = not comfortable at all, 2 = kind of comfortable, 3 = somewhat comfortable, 4 = comfortable, 5 = very comfortable).

&nbsp;

3. Rate your comfort level with `R Studio` and computer programming in general now (1 = not comfortable at all, 2 = kind of comfortable, 3 = somewhat comfortable, 4 = comfortable, 5 = very comfortable).

&nbsp;

4. State anything that you really like about the course (leave blank if there isn't anything that you really like). 

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

5. State anything that you wish would change in the course (leave blank if there isn't anything that you wish would change).

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

6. This is my first time teaching in this renovated classroom. Are there any issues you are having related to the room configuration? 

&nbsp;

_Turn page over_

\pagebreak

6. The pace of this class is.... (1) much too quick, (2) a little too quick, (3) about the right pace, (4) a little too slow, or (5) much too slow.

&nbsp;

&nbsp;

7. The level of this course is..... (1) much too easy, (2) a little too easy, (3) about right, (4) a little too difficult, or (5) much too difficult.

&nbsp;

&nbsp;

8. Presumably you are taking 3 other courses (but possibly one more or one less) besides this course. If you were to rank your 4 courses in terms of challenge/difficulty, where a rank of 1 goes to the most challenging course and a rank of 4 goes to the least challenging course, what would this course's rank be?  

&nbsp;

&nbsp;

9. About how many hours per week do you spend on this course, __including__ time spent in class? (So, if you do nothing except go to class, you would spend 3 hours on this course). This will likely vary from week to week (you probably spent more time on this class for the first project than for other weeks), but try to think about an __average__.

&nbsp;

&nbsp;

10. Presumably you are taking 3 other courses (but possibly one more or one less) besides this course. If you were to rank your 4 courses in terms of the amount of time you spend on each course, where a rank of 1 goes to the course that you spend the most time on and a rank of 4 goes to the course that you spend the least time on, what would this course's rank be?  

&nbsp;

11. Assign yourself a letter grade (A-F) based on your work and effort in the course so far.

&nbsp;

&nbsp;

12. Why did you assign yourself that grade?

&nbsp;

&nbsp;

&nbsp;

&nbsp;

13. Is there anything that I can do to make your learning and experience in this class better? Are there any other thoughts you have?

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

