---
title: "STAT 234: Participation Rubric"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

You will be graded on your class participation by both yourself and me using the following rubric. These evaluations will be kept confidential. 

While my assessment will ultimately be what is recorded as your grade for participation, it is informative to evaluate yourself with regard to the following categories.

Your Name: _______________________

Your Score (out of 20): ____________________________

__Directions__: Circle one of the following categories for each of the 5 assessment categories. Example: If you thought that you were late to class more than once so far, you would circle the column under "Good" for that category.

| Category | Excellent (4) | Good (2) | Poor (0) |
| ------- | ------------------- | ------------------- | --------------------- |
| Attendance | I attended most of the classes, with at most one absence. If there is more than one absence, a valid reason was given for each absence. | I missed more than one class. | I missed more than three classes. |
| Tardiness | I was on time to all classes except perhaps once or twice during the time frame of this evaluation. | I was late to class more than twice. | I was late to class more than four times. |
| Engagement | When present, I gave effort for problems done in individually or with a partner or small group. | When present, I sometimes gave effort for problems done individually or in groups but other times was distracted or took breaks. | When present, I rarely gave effort for the problems done individually or in groups.|
| Electronics | I almost never was distracted by my phone, tablet, or laptop during class. | I was only occasionally distracted by my phone, tablet, or laptop during class. | I was often distracted by my phone, tablet, or laptop during class. |
| Attitude | I displayed a positive attitude for nearly all of the classes where I was present. | I sometimes displayed a positive attitude but other times was quite negative. | I displayed a negative attitude during most of the classes. |
