---
title:  "Aesthetics in `ggplot2` Solutions"
format: 
  html:
    self-contained: true
execute:
  echo: true
  warning: false
  fig-height: 3
---

```{r}
library(tidyverse)
fitness_full <- read_csv(here::here("data/higham_fitness_clean.csv"),
                         col_types = list(stepgoal = col_factor())) |>
  mutate(weekend_ind = case_when(weekday == "Sat" | weekday == "Sun" ~ "weekend",
                                 TRUE ~ "weekday"))
```

__Exercise 1__. 

```{r}
ggplot(data = fitness_full,
       aes(x = Start, y = active_cals)) +
  geom_point(size = 1.9, shape = 4)
```

__Exercise 2__. 

```{r}
ggplot(data = fitness_full,
       aes(x = Start, y = active_cals)) +
  geom_point() +
  geom_smooth(linewidth = 1.4)
```

__Exercise 3__. 

```{r}
ggplot(data = fitness_full) +
  geom_point(aes(x = Start, y = active_cals)) +
  geom_line(aes(x = Start, y = active_cals))
```

__Exercise 4__.

```{r}
ggplot(data = fitness_full, aes(x = weekday, y = steps)) +
  geom_boxplot(fill = "coral1", colour = "black")
```
