---
title:  "`R` Basics Solutions"
format: 
  html:
    self-contained: true
execute:
  echo: true
  warning: false
  fig-height: 3
---

```{r, message = FALSE}
library(tidyverse)
fitness_df <- read_csv(here("data/higham_fitness_notclean.csv"))
```

__Exercise 1__. 

```{r, echo = TRUE}
fitness_df <- fitness_df |> mutate(weekday = as.factor(weekday))
ggplot(data = fitness_df, aes(x = active_cals)) +
  geom_freqpoly(aes(group = weekday, colour = weekday)) +
  theme_minimal()
```

__Exercise 2__. 

Logical (`<lgl>`).

__Exercise 3__. Convert `stepgoal` to the class that is the answer to the previous exercise. Using this new variable, calculate the total number of days where the goal was met and the proportion of the days where the goal was met.

```{r}
fitness_df |> mutate(stepgoal_lgl = as.logical(stepgoal)) |>
  relocate(stepgoal_lgl) |>
  summarise(total_days = sum(stepgoal_lgl),
            prop_days = mean(stepgoal_lgl))
```

__Exercise 4__. 

`slice()` for the rows and `select()` for the columns.

__Exercise 5__. 

```{r}
videogame_df[1:100, ] ## 1
videogame_df |> slice(1:100) ## 2
```

__Exercise 6__. 

```{r}
videogame_df[ ,-5] ## 1
videogame_df |> select(-5) ## 2
```

__Exercise 7__.

```{r}
summary(videogame_df$metascore)
```
