---
title: "Workflow Solutions"
format: 
  html:
    self-contained: true
execute:
  echo: true
  warning: false
  fig-height: 3
---

```{r}
library(tidyverse)
```

__Exercise 1__. Solution not given but you should now have a `Quizzes` folder with at least one Quiz `.qmd` file that renders correctly!

__Exercise 2__. Answers will vary.

```{r}
cars_heavy <- mtcars |> filter(wt > 3)
```

```{r}
disp_summary <- mtcars |> group_by(am) |>
  summarise(mean_disp = mean(disp),
            med_disp = median(disp),
            sd_disp = sd(disp))
```

__Exercise 3__. 

```{r}
ggplot(data = mtcars, aes(x = mpg)) +
  geom_histogram(colour = "black", fill = "white", bins = 15) +
  facet_wrap(~ cyl, ncol = 1)
```

__Exercise 4__.

```{r}
library(here)
stat113_df <- read_csv(here("data/stat113.csv"))
```

```{r}
#| eval: false
library(skimr)
skim(stat113_df)
```

Three of the five categorical variables have at least one `NA`, as seen in the `n_missing` column of the `skim()` output.

All numeric variables have at least one `NA` value.

__Exercise 5__. Answers will vary.

```{r}
tibble(class = c("STAT 113", "STAT 213", "DATA/STAT 234", "DATA/STAT 334"),
       time = c(5, 7, 8, 7))
```
