<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DATA / STAT 234 - 3&nbsp; Wrangling with dplyr</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-comm.html" rel="next">
<link href="./02-ggplot2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-intro.html">The Core</a></li><li class="breadcrumb-item"><a href="./03-dplyr.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Wrangling with `dplyr`</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DATA / STAT 234</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus and Course Information</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">The Core</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Plotting with <code>ggplot2</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-dplyr.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Wrangling with <code>dplyr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-comm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Communication with <code>Quarto</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Workflow and Other Skills</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Data Wrangling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-tidyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tidying with <code>tidyr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Coding in Base <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-forcats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Factors with <code>forcats</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-ethics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Data Ethics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data Import</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-merging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Merging with <code>dplyr</code></span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Special Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-lubridate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Dates with <code>lubridate</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-stringr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Text Data with <code>tidytext</code> and <code>stringr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-knn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Predictive Modeling with knn</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-connections.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Connections to STAT 113, STAT 213, and CS 140</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-sql.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Introduction to SQL with <code>dbplyr</code></span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#filterslice-select-arrange-and-piping" id="toc-filterslice-select-arrange-and-piping" class="nav-link active" data-scroll-target="#filterslice-select-arrange-and-piping"><span class="header-section-number">3.1</span> <code>filter()</code>,<code>slice()</code>, <code>select()</code>, <code>arrange()</code>, and Piping</a>
  <ul class="collapse">
<li><a href="#filter-and-slice-choosing-rows" id="toc-filter-and-slice-choosing-rows" class="nav-link" data-scroll-target="#filter-and-slice-choosing-rows"><span class="header-section-number">3.1.1</span> <code>filter()</code> and <code>slice()</code>: Choosing Rows</a></li>
  <li><a href="#arrange-ordering-rows" id="toc-arrange-ordering-rows" class="nav-link" data-scroll-target="#arrange-ordering-rows"><span class="header-section-number">3.1.2</span> <code>arrange()</code>: Ordering Rows</a></li>
  <li><a href="#select-choosing-columns" id="toc-select-choosing-columns" class="nav-link" data-scroll-target="#select-choosing-columns"><span class="header-section-number">3.1.3</span> <code>select()</code>: Choosing Columns</a></li>
  <li><a href="#assigning-a-data-frame-a-name" id="toc-assigning-a-data-frame-a-name" class="nav-link" data-scroll-target="#assigning-a-data-frame-a-name"><span class="header-section-number">3.1.4</span> Assigning a Data Frame a Name</a></li>
  <li><a href="#more-about-the-pipe" id="toc-more-about-the-pipe" class="nav-link" data-scroll-target="#more-about-the-pipe"><span class="header-section-number">3.1.5</span> More about the Pipe</a></li>
  </ul>
</li>
  <li>
<a href="#practice" id="toc-practice" class="nav-link" data-scroll-target="#practice"><span class="header-section-number">3.2</span> Practice</a>
  <ul class="collapse">
<li><a href="#class-exercises" id="toc-class-exercises" class="nav-link" data-scroll-target="#class-exercises"><span class="header-section-number">3.2.1</span> Class Exercises</a></li>
  <li><a href="#your-turn" id="toc-your-turn" class="nav-link" data-scroll-target="#your-turn"><span class="header-section-number">3.2.2</span> Your Turn</a></li>
  </ul>
</li>
  <li>
<a href="#mutate-group_by-summarise-and-missing-values" id="toc-mutate-group_by-summarise-and-missing-values" class="nav-link" data-scroll-target="#mutate-group_by-summarise-and-missing-values"><span class="header-section-number">3.3</span> <code>mutate()</code>, <code>group_by()</code>, <code>summarise()</code>, and Missing Values</a>
  <ul class="collapse">
<li><a href="#mutate-create-variables" id="toc-mutate-create-variables" class="nav-link" data-scroll-target="#mutate-create-variables"><span class="header-section-number">3.3.1</span> <code>mutate()</code>: Create Variables</a></li>
  <li><a href="#summarise-create-summaries" id="toc-summarise-create-summaries" class="nav-link" data-scroll-target="#summarise-create-summaries"><span class="header-section-number">3.3.2</span> <code>summarise()</code>: Create Summaries</a></li>
  <li><a href="#group_by-groups" id="toc-group_by-groups" class="nav-link" data-scroll-target="#group_by-groups"><span class="header-section-number">3.3.3</span> <code>group_by()</code>: Groups</a></li>
  <li><a href="#missing-values" id="toc-missing-values" class="nav-link" data-scroll-target="#missing-values"><span class="header-section-number">3.3.4</span> Missing Values</a></li>
  </ul>
</li>
  <li>
<a href="#practice-1" id="toc-practice-1" class="nav-link" data-scroll-target="#practice-1"><span class="header-section-number">3.4</span> Practice</a>
  <ul class="collapse">
<li><a href="#class-exercises-1" id="toc-class-exercises-1" class="nav-link" data-scroll-target="#class-exercises-1"><span class="header-section-number">3.4.1</span> Class Exercises</a></li>
  <li><a href="#your-turn-1" id="toc-your-turn-1" class="nav-link" data-scroll-target="#your-turn-1"><span class="header-section-number">3.4.2</span> Your Turn</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-dplyr" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Wrangling with <code>dplyr</code></span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p><strong>Goals:</strong></p>
<ul>
<li>Use the <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice()</a></code> functions to keep certain rows of a data frame.</li>
<li>Use the <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> function to keep certain columns of a data frame.</li>
<li>Use the <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> function to sort a data frame.</li>
<li>Explain what the pipe operator <code>|&gt;</code> does and explain when you can and cannot use the pipe operator.</li>
<li>Combine the above goals with plotting to explore the <code>babynames</code> data set.</li>
</ul>
<section id="filterslice-select-arrange-and-piping" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="filterslice-select-arrange-and-piping">
<span class="header-section-number">3.1</span> <code>filter()</code>,<code>slice()</code>, <code>select()</code>, <code>arrange()</code>, and Piping</h2>
<p>Throughout this chapter, we will use the <code>babynames</code> data set in the <code>babynames</code> <code>R</code> package. To begin, install the <code>babynames</code> package by typing <code>install.packages("babynames")</code> in your bottom-left console window, and then load the <code>babynames</code> package in with</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/hadley/babynames">babynames</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Read about the data set by typing <code><a href="https://rdrr.io/pkg/babynames/man/babynames.html">?babynames</a></code> in your bottom-left window of <code>R Studio</code>. We see that this data set contains baby name data provided by the SSA in the United States dating back to 1880:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span></span>
<span><span class="co">#&gt; # A tibble: 1,924,665 × 5</span></span>
<span><span class="co">#&gt;    year sex   name          n   prop</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  1880 F     Mary       7065 0.0724</span></span>
<span><span class="co">#&gt; 2  1880 F     Anna       2604 0.0267</span></span>
<span><span class="co">#&gt; 3  1880 F     Emma       2003 0.0205</span></span>
<span><span class="co">#&gt; 4  1880 F     Elizabeth  1939 0.0199</span></span>
<span><span class="co">#&gt; 5  1880 F     Minnie     1746 0.0179</span></span>
<span><span class="co">#&gt; 6  1880 F     Margaret   1578 0.0162</span></span>
<span><span class="co">#&gt; # ℹ 1,924,659 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are many interesting and informative plots that we could make with this data set, but most require some data wrangling first. This chapter will provide the foundation for such wrangling skills.</p>
<p>Before we begin, we also need to load in the <code>tidyverse</code> package so that we can use the <code>dplyr</code> functions.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="filter-and-slice-choosing-rows" class="level3" data-number="3.1.1"><h3 data-number="3.1.1" class="anchored" data-anchor-id="filter-and-slice-choosing-rows">
<span class="header-section-number">3.1.1</span> <code>filter()</code> and <code>slice()</code>: Choosing Rows</h3>
<p>There are a lot of commonly used <code>dplyr</code> wrangling functions, but we need to start somewhere! We will begin with two functions used to choose rows to keep in the data frame: <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>, which keeps rows based on a condition that is provided, and <code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice()</a></code>, which keeps rows based on row numbers that are provided.</p>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> is a way to keep rows by specifying a <strong>condition</strong> related to one or more of the variables in the data set.</p>
</div>
</div>
<p>We can keep rows based on a categorical variable or a quantitative variable or a combination of any number of categorical and quantitative variables. <code>R</code> uses the following symbols to make comparisons:</p>
<ul>
<li>
<code>&lt;</code> and <code>&lt;=</code> for less than and less than or equal to, respectively</li>
<li>
<code>&gt;</code> and <code>&gt;=</code> for greater than and greater than or equal to, respectively</li>
<li>
<code>==</code> for equal to (careful: equal to is a double equal sign <code>==</code>)</li>
<li>
<code>!=</code> for not equal to (in general, <code>!</code> denotes “not”)</li>
</ul>
<p>The easiest way to see how filter works is with some examples. The following line of code <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>s the <code>babynames</code> data set based on a condition. See if you can guess what the following statement does before running the code.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">name</span> <span class="op">==</span> <span class="st">"Matthew"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We’re seeing our first of many, many, many, many, many, many, many instances of using <code>|&gt;</code> to “pipe.” Piping is a really convenient, easy-to-read way to build a sequence of commands. How you can read the above code is:</p>
<ol type="1">
<li><p>Take the <code>babynames</code> data frame object and with <code>babynames</code>, <strong>and then</strong></p></li>
<li><p>perform a <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> step to keep only the rows where <code>name</code> is <code>Matthew</code>.</p></li>
</ol>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>“and then”</strong> phrase is the most commonly used phrase to explain how to read the pipe <code>|&gt;</code> in a line of code.</p>
</div>
</div>
<p>Examine the following four <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> statements and see if you can guess what each one is doing before running the code.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">year</span> <span class="op">&gt;=</span> <span class="fl">2000</span><span class="op">)</span></span>
<span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">sex</span> <span class="op">!=</span> <span class="st">"M"</span><span class="op">)</span></span>
<span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">prop</span> <span class="op">&gt;</span> <span class="fl">0.05</span><span class="op">)</span></span>
<span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">year</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that some things put in quotes, like <code>"M"</code> while some things aren’t, like <code>2000</code>. Generally, if we are filtering by a numeric variable, like <code>prop</code>, any value used in the filtering statement does not go in quotes, while if we are filtering by a categorical variable, like <code>sex</code> or <code>name</code>, the value used in the filtering statement does go in quotes.</p>
<p>We can also combine conditions on multiple variables in <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> using Boolean operators. Look at the Venn diagrams in <code>R</code> for Data Science to learn about the various Boolean operators you can use in <code>R</code>: <a href="https://r4ds.had.co.nz/transform.html#logical-operators" target="_blank">https://r4ds.had.co.nz/transform.html#logical-operators</a>. The Boolean operators can be used in other functions in <code>R</code> as well, as we will see in the next section with <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>.</p>
<p>The following gives some examples. See if you can figure out what each line of code is doing before running it.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">n</span> <span class="op">&gt;</span> <span class="fl">20000</span> <span class="op">|</span> <span class="va">prop</span> <span class="op">&gt;</span> <span class="fl">0.05</span><span class="op">)</span></span>
<span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">sex</span> <span class="op">==</span> <span class="st">"F"</span> <span class="op">&amp;</span> <span class="va">name</span> <span class="op">==</span> <span class="st">"Mary"</span><span class="op">)</span></span>
<span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">sex</span> <span class="op">==</span> <span class="st">"F"</span> <span class="op">&amp;</span> <span class="va">name</span> <span class="op">==</span> <span class="st">"Mary"</span> <span class="op">&amp;</span> <span class="va">prop</span> <span class="op">&gt;</span> <span class="fl">0.05</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>While <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> lets us choose which rows in a data set to keep based on a <strong>condition</strong>, <code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice()</a></code> allows us to specify the <strong>row numbers</strong> corresponding to rows that we want to keep.</p>
</div>
</div>
<p>For example, suppose that we only want to keep the first 5 rows of the <code>babynames</code> data:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">5</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 5</span></span>
<span><span class="co">#&gt;    year sex   name          n   prop</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  1880 F     Mary       7065 0.0724</span></span>
<span><span class="co">#&gt; 2  1880 F     Anna       2604 0.0267</span></span>
<span><span class="co">#&gt; 3  1880 F     Emma       2003 0.0205</span></span>
<span><span class="co">#&gt; 4  1880 F     Elizabeth  1939 0.0199</span></span>
<span><span class="co">#&gt; 5  1880 F     Minnie     1746 0.0179</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code><a href="https://rdrr.io/r/base/c.html">c()</a></code> function is used here to bind the numbers <code>1, 2, 3, 4, 5</code> into a <strong>vector</strong>. <code><a href="https://rdrr.io/r/base/c.html">c()</a></code> actually stands for “concatenate.” We can alternatively use <code>slice(1:5)</code>, which is shorthand for <code>slice(c(1, 2, 3, 4, 5))</code>. The <code>:</code> is useful for larger numbers of rows that we might want to keep. For example, <code>slice(1:1000)</code> is much easier than <code>slice(c(1, 2, 3, 4, ...., 999, 1000))</code>. While <code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice()</a></code> is useful, it is relatively simple. We’ll come back to it again in a few weeks as well when we discuss subsetting in base <code>R</code>.</p>
<p><strong>Exercise 1</strong>. Use <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> on the <code>babynames</code> data set to only keep rows with your name. (Note that, the data set has a large variety of names, but, if there were fewer than 5 people born in the United States with your name every year, then your name might not appear in the data set. In that case, just use a different name that interests you!).</p>
<p><strong>Exercise 2</strong>. Use <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> to only keep rows in the <code>babynames</code> data set from the <code>year</code> <code>2000</code> onward.</p>
<p><strong>Exercise 3</strong>. Use <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> to only keep rows in <code>babynames</code> with your name from Exercise 1 <strong>and</strong> that have a <code>year</code> from <code>2000</code> onward.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint (only if you get stuck)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You will need to use the <code>&amp;</code> Boolean operator to combine your conditions from the previous two exercises.</p>
</div>
</div>
</div>
<p><strong>Exercise 4</strong>. Use <code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice()</a></code> to keep the first <code>20</code> rows of <code>babynames</code>.</p>
</section><section id="arrange-ordering-rows" class="level3" data-number="3.1.2"><h3 data-number="3.1.2" class="anchored" data-anchor-id="arrange-ordering-rows">
<span class="header-section-number">3.1.2</span> <code>arrange()</code>: Ordering Rows</h3>
<p>The <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> function allows us to order rows in the data set using one or more variables. The function is very straightforward: we only need to provide the name of the variable that we want to order by. For example,</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1,924,665 × 5</span></span>
<span><span class="co">#&gt;    year sex   name          n      prop</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;     &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  1880 F     Adelle        5 0.0000512</span></span>
<span><span class="co">#&gt; 2  1880 F     Adina         5 0.0000512</span></span>
<span><span class="co">#&gt; 3  1880 F     Adrienne      5 0.0000512</span></span>
<span><span class="co">#&gt; 4  1880 F     Albertine     5 0.0000512</span></span>
<span><span class="co">#&gt; 5  1880 F     Alys          5 0.0000512</span></span>
<span><span class="co">#&gt; 6  1880 F     Ana           5 0.0000512</span></span>
<span><span class="co">#&gt; # ℹ 1,924,659 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>orders the <code>babynames</code> data so that <code>n</code>, the number of babies, goes from smallest to largest. If we want to <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> by descending order of a variable, we just wrap the name of the variable we are ordering by with <code><a href="https://dplyr.tidyverse.org/reference/desc.html">desc()</a></code> for “descending:”</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1,924,665 × 5</span></span>
<span><span class="co">#&gt;    year sex   name        n   prop</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;int&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  1947 F     Linda   99686 0.0548</span></span>
<span><span class="co">#&gt; 2  1948 F     Linda   96209 0.0552</span></span>
<span><span class="co">#&gt; 3  1947 M     James   94756 0.0510</span></span>
<span><span class="co">#&gt; 4  1957 M     Michael 92695 0.0424</span></span>
<span><span class="co">#&gt; 5  1947 M     Robert  91642 0.0493</span></span>
<span><span class="co">#&gt; 6  1949 F     Linda   91016 0.0518</span></span>
<span><span class="co">#&gt; # ℹ 1,924,659 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Exercise 5</strong>. Use <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> to sort the data frame so that it is in descending order by the <code>prop</code> variable. This allows us to examine the names with the highest proportion of babies given that name for that given <code>year</code>.</p>
<p><strong>Exercise 6</strong>. Use <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> on the categorical variable <code>name</code>. What does <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> seem to do on a categorical variable?</p>
</section><section id="select-choosing-columns" class="level3" data-number="3.1.3"><h3 data-number="3.1.3" class="anchored" data-anchor-id="select-choosing-columns">
<span class="header-section-number">3.1.3</span> <code>select()</code>: Choosing Columns</h3>
<p>We might also be interested in getting rid of some of the columns in a data set. One reason to do this is if there are an overwhelming (30+) columns in a data set, but we know that we just need a few of them. The easiest way to use <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> is to just input the names of the columns that you want to keep. For example, if we were only interested in the <code>name</code> and <code>n</code> variables, we could make a data frame with only those variables with:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">name</span>, <span class="va">n</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1,924,665 × 2</span></span>
<span><span class="co">#&gt;   name          n</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;     &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 Mary       7065</span></span>
<span><span class="co">#&gt; 2 Anna       2604</span></span>
<span><span class="co">#&gt; 3 Emma       2003</span></span>
<span><span class="co">#&gt; 4 Elizabeth  1939</span></span>
<span><span class="co">#&gt; 5 Minnie     1746</span></span>
<span><span class="co">#&gt; 6 Margaret   1578</span></span>
<span><span class="co">#&gt; # ℹ 1,924,659 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We might also want to use <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> to get rid of one or more columns. If this is the case, we denote any column you want to get rid of with <code>-</code>. For example, we might want to get rid of the <code>sex</code> column and the <code>prop</code> column with</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">sex</span>, <span class="op">-</span><span class="va">prop</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1,924,665 × 3</span></span>
<span><span class="co">#&gt;    year name          n</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt;     &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1  1880 Mary       7065</span></span>
<span><span class="co">#&gt; 2  1880 Anna       2604</span></span>
<span><span class="co">#&gt; 3  1880 Emma       2003</span></span>
<span><span class="co">#&gt; 4  1880 Elizabeth  1939</span></span>
<span><span class="co">#&gt; 5  1880 Minnie     1746</span></span>
<span><span class="co">#&gt; 6  1880 Margaret   1578</span></span>
<span><span class="co">#&gt; # ℹ 1,924,659 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> comes with many useful helper functions, but these are oftentimes not needed. One of the helper functions that <strong>is</strong> actually often useful is <code><a href="https://tidyselect.r-lib.org/reference/everything.html">everything()</a></code>, which selects all columns in a data frame. This can be used to help re-order columns if you have a particular column that you want to appear first:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">name</span>, <span class="fu"><a href="https://tidyselect.r-lib.org/reference/everything.html">everything</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1,924,665 × 5</span></span>
<span><span class="co">#&gt;   name       year sex       n   prop</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;int&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 Mary       1880 F      7065 0.0724</span></span>
<span><span class="co">#&gt; 2 Anna       1880 F      2604 0.0267</span></span>
<span><span class="co">#&gt; 3 Emma       1880 F      2003 0.0205</span></span>
<span><span class="co">#&gt; 4 Elizabeth  1880 F      1939 0.0199</span></span>
<span><span class="co">#&gt; 5 Minnie     1880 F      1746 0.0179</span></span>
<span><span class="co">#&gt; 6 Margaret   1880 F      1578 0.0162</span></span>
<span><span class="co">#&gt; # ℹ 1,924,659 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The previous line of code puts <code>name</code> as the first variable in the data frame.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For data frames with only a few columns, re-ordering the columns is generally not that useful, but, for data frames with hundreds or thousands of columns, moving variables of interest to the beginning of the data frame helps us view these variables more readily.</p>
</div>
</div>
<p><strong>Exercise 7</strong>. Use <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> to keep only the <code>year</code>, <code>name</code> and <code>prop</code> variables in two ways: (1) keep <code>year</code>, <code>name</code>, and <code>prop</code> directly by specifying these variable names in <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> and (2) keep only <code>year</code>, <code>name</code>, and <code>prop</code> indirectly by specifying that <code>sex</code>, and <code>n</code> should be dropped from the data frame.</p>
</section><section id="assigning-a-data-frame-a-name" class="level3" data-number="3.1.4"><h3 data-number="3.1.4" class="anchored" data-anchor-id="assigning-a-data-frame-a-name">
<span class="header-section-number">3.1.4</span> Assigning a Data Frame a Name</h3>
<p>Up until now, we have not assigned any of the new data frames we are creating a name. For example, with</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">name</span> <span class="op">==</span> <span class="st">"Matthew"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 212 × 5</span></span>
<span><span class="co">#&gt;    year sex   name        n     prop</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;int&gt;    &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  1880 M     Matthew   113 0.000954</span></span>
<span><span class="co">#&gt; 2  1881 M     Matthew    80 0.000739</span></span>
<span><span class="co">#&gt; 3  1882 M     Matthew   109 0.000893</span></span>
<span><span class="co">#&gt; 4  1883 M     Matthew    86 0.000765</span></span>
<span><span class="co">#&gt; 5  1884 M     Matthew   117 0.000953</span></span>
<span><span class="co">#&gt; 6  1885 M     Matthew   111 0.000957</span></span>
<span><span class="co">#&gt; # ℹ 206 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>we get a printout of the data with only the <code>name</code> <code>Matthew</code>, but, the data frame object is not assigned a name at all. So, we cannot use <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code> to make a plot of <code>n</code> only for the name <code>Matthew</code> because we do not have a named data set that only has the name <code>Matthew</code>. In other words, <code>R</code> performs the <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>, but the filtered data frame doesn’t get saved to any particular named object. If we want to “save” the new data set for future use (like in a plot command), then we can use the assignment operator, <code>&lt;-</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames_matthew</span> <span class="op">&lt;-</span> <span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">name</span> <span class="op">==</span> <span class="st">"Matthew"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the previous chunk, we assign the data frame with only <code>Matthew</code> names to the name <code>babynames_matthew</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames_matthew</span></span>
<span><span class="co">#&gt; # A tibble: 212 × 5</span></span>
<span><span class="co">#&gt;    year sex   name        n     prop</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;int&gt;    &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  1880 M     Matthew   113 0.000954</span></span>
<span><span class="co">#&gt; 2  1881 M     Matthew    80 0.000739</span></span>
<span><span class="co">#&gt; 3  1882 M     Matthew   109 0.000893</span></span>
<span><span class="co">#&gt; 4  1883 M     Matthew    86 0.000765</span></span>
<span><span class="co">#&gt; 5  1884 M     Matthew   117 0.000953</span></span>
<span><span class="co">#&gt; 6  1885 M     Matthew   111 0.000957</span></span>
<span><span class="co">#&gt; # ℹ 206 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can really use almost any name we would like but it’s more helpful to use a name that makes sense (<code>babynames_matthew</code>) than a name that is meaningless.</p>
</div>
</div>
<p>An example of giving a data frame a meaningless name would be:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">take_it_kronk_feel_the_power</span> <span class="op">&lt;-</span> <span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">name</span> <span class="op">==</span> <span class="st">"Matthew"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can use the data frame <code>take_it_kronk_feel_the_power</code> in the same way as <code>babynames_matthew</code>, but <code>take_it_kronk_feel_the_power</code> is not as easy to remember and doesn’t make any sense in this context.</p>
<p><strong>Exercise 8</strong>. Name your data frame that you created from <strong>Exercise 1</strong>. Then, type in the name you assigned to the data frame to verify that you can see some printed out data.</p>
</section><section id="more-about-the-pipe" class="level3" data-number="3.1.5"><h3 data-number="3.1.5" class="anchored" data-anchor-id="more-about-the-pipe">
<span class="header-section-number">3.1.5</span> More about the Pipe</h3>
<p>We are jumping straight into using piping, but we do want to have an appreciation on how terrible life would be without it. What piping does is make whatever is given before the <code>|&gt;</code> pipe the first argument of whatever function follows the <code>|&gt;</code>. So, for a toy data frame named <code>df</code> with variable <code>xvar</code>,</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">xvar</span> <span class="op">&lt;=</span> <span class="fl">3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>is equivalent to</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df</span>, <span class="va">xvar</span> <span class="op">&lt;=</span> <span class="fl">3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>It might also help to use an analogy when thinking about piping. Consider the Ke$ha’s morning routine in the opening of the song Tik Tok. If we were to write her morning routine in terms of piping,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>kesha <span class="sc">|&gt;</span> <span class="fu">wake_up</span>(<span class="at">time =</span> <span class="st">"morning"</span>, <span class="at">feels_like =</span> <span class="st">"P-Diddy"</span>) <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">grab</span>(glasses) <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">brush</span>(teeth, <span class="at">item =</span> <span class="st">"jack"</span>, <span class="at">unit =</span> <span class="st">"bottle"</span>) <span class="sc">|&gt;</span> ....</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Kesha first wakes up in the morning, <em>and then</em> the Kesha that has woken up grabs her glasses, <em>and then</em> the Kesha who has woken up and has grabbed her glasses proceeds to brush her teeth, etc.</p>
<p>The pipe operator <code>|&gt;</code> is loaded automatically with <code>R</code>. We will heavily use the pipe throughout the entire semester so it’s worth it to delve a little deeper into what it is here. We will use the fitness data to further explore the pipe. Read in the data with</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fitness_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://raw.githubusercontent.com/highamm/ds234_quarto/main/data_online/higham_fitness_clean.csv"</span>,</span>
<span>                       col_types <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>stepgoal <span class="op">=</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/parse_factor.html">col_factor</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">fitness_df</span></span>
<span><span class="co">#&gt; # A tibble: 1,722 × 9</span></span>
<span><span class="co">#&gt;   Start      active_cals distance flights  steps month weekday dayofyear</span></span>
<span><span class="co">#&gt;   &lt;date&gt;           &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 2018-11-28        57.8    0.930       0  1885. Nov   Wed           332</span></span>
<span><span class="co">#&gt; 2 2018-11-29       509.     4.64       18  8953. Nov   Thu           333</span></span>
<span><span class="co">#&gt; 3 2018-11-30       599.     6.05       12 11665  Nov   Fri           334</span></span>
<span><span class="co">#&gt; 4 2018-12-01       661.     6.80        6 12117  Dec   Sat           335</span></span>
<span><span class="co">#&gt; 5 2018-12-02       527.     4.61        1  8925. Dec   Sun           336</span></span>
<span><span class="co">#&gt; 6 2018-12-03       550.     3.96        2  7205  Dec   Mon           337</span></span>
<span><span class="co">#&gt; # ℹ 1,716 more rows</span></span>
<span><span class="co">#&gt; # ℹ 1 more variable: stepgoal &lt;fct&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Thus far, we have used a single pipe <code>|&gt;</code> to do one task, but, we can string together multiple <code>dplyr</code> functions with multiple <code>|&gt;</code> statements. For example, suppose that we wanted to keep only the <code>weekday</code>s that were <code>Sat</code> and <code>Sun</code>, <strong>and then</strong>, order the data set so that it was in descending order of <code>steps</code> taken:</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fitness_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">weekday</span> <span class="op">==</span> <span class="st">"Sat"</span> <span class="op">|</span> <span class="va">weekday</span> <span class="op">==</span> <span class="st">"Sun"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">steps</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 492 × 9</span></span>
<span><span class="co">#&gt;   Start      active_cals distance flights  steps month weekday dayofyear</span></span>
<span><span class="co">#&gt;   &lt;date&gt;           &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 2023-07-15       2291.     18.0     193 32589. Jul   Sat           196</span></span>
<span><span class="co">#&gt; 2 2019-08-11       1385.     15.8     173 29480. Aug   Sun           223</span></span>
<span><span class="co">#&gt; 3 2019-04-14       1767.     17.9       1 25578  Apr   Sun           104</span></span>
<span><span class="co">#&gt; 4 2018-12-15       1091.     11.2      27 21224. Dec   Sat           349</span></span>
<span><span class="co">#&gt; 5 2022-05-29       1291.     11.8     103 20853  May   Sun           149</span></span>
<span><span class="co">#&gt; 6 2019-02-10       1392.     12.8       5 20700. Feb   Sun            41</span></span>
<span><span class="co">#&gt; # ℹ 486 more rows</span></span>
<span><span class="co">#&gt; # ℹ 1 more variable: stepgoal &lt;fct&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This reads: “take <code>fitness_df</code> and then <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> it to keep only Saturdays and Sundays and then sort it in descending order of <code>steps</code>.”</p>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consecutive pipes build on each other: we can slowly build out what the pipe is doing step-by-step. Running code “pipe by pipe” can be a very helpful way to understand what each consecutive piping statement is doing.</p>
</div>
</div>
<p>The code</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fitness_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">weekday</span> <span class="op">==</span> <span class="st">"Sat"</span> <span class="op">|</span> <span class="va">weekday</span> <span class="op">==</span> <span class="st">"Sun"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 492 × 9</span></span>
<span><span class="co">#&gt;   Start      active_cals distance flights  steps month weekday dayofyear</span></span>
<span><span class="co">#&gt;   &lt;date&gt;           &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 2018-12-01        661.     6.80       6 12117  Dec   Sat           335</span></span>
<span><span class="co">#&gt; 2 2018-12-02        527.     4.61       1  8925. Dec   Sun           336</span></span>
<span><span class="co">#&gt; 3 2018-12-08        775.     6.46       0  8834. Dec   Sat           342</span></span>
<span><span class="co">#&gt; 4 2018-12-09        341.     2.81       0  5265  Dec   Sun           343</span></span>
<span><span class="co">#&gt; 5 2018-12-15       1091.    11.2       27 21224. Dec   Sat           349</span></span>
<span><span class="co">#&gt; 6 2018-12-16       1029.     8.84      79 16376  Dec   Sun           350</span></span>
<span><span class="co">#&gt; # ℹ 486 more rows</span></span>
<span><span class="co">#&gt; # ℹ 1 more variable: stepgoal &lt;fct&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>is equivalent to:</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">fitness_df</span>, <span class="va">weekday</span> <span class="op">==</span> <span class="st">"Sat"</span> <span class="op">|</span> <span class="va">weekday</span> <span class="op">==</span> <span class="st">"Sun"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 492 × 9</span></span>
<span><span class="co">#&gt;   Start      active_cals distance flights  steps month weekday dayofyear</span></span>
<span><span class="co">#&gt;   &lt;date&gt;           &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 2018-12-01        661.     6.80       6 12117  Dec   Sat           335</span></span>
<span><span class="co">#&gt; 2 2018-12-02        527.     4.61       1  8925. Dec   Sun           336</span></span>
<span><span class="co">#&gt; 3 2018-12-08        775.     6.46       0  8834. Dec   Sat           342</span></span>
<span><span class="co">#&gt; 4 2018-12-09        341.     2.81       0  5265  Dec   Sun           343</span></span>
<span><span class="co">#&gt; 5 2018-12-15       1091.    11.2       27 21224. Dec   Sat           349</span></span>
<span><span class="co">#&gt; 6 2018-12-16       1029.     8.84      79 16376  Dec   Sun           350</span></span>
<span><span class="co">#&gt; # ℹ 486 more rows</span></span>
<span><span class="co">#&gt; # ℹ 1 more variable: stepgoal &lt;fct&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then,</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">fitness_df</span>, <span class="va">weekday</span> <span class="op">==</span> <span class="st">"Sat"</span> <span class="op">|</span> <span class="va">weekday</span> <span class="op">==</span> <span class="st">"Sun"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">steps</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 492 × 9</span></span>
<span><span class="co">#&gt;   Start      active_cals distance flights  steps month weekday dayofyear</span></span>
<span><span class="co">#&gt;   &lt;date&gt;           &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 2023-07-15       2291.     18.0     193 32589. Jul   Sat           196</span></span>
<span><span class="co">#&gt; 2 2019-08-11       1385.     15.8     173 29480. Aug   Sun           223</span></span>
<span><span class="co">#&gt; 3 2019-04-14       1767.     17.9       1 25578  Apr   Sun           104</span></span>
<span><span class="co">#&gt; 4 2018-12-15       1091.     11.2      27 21224. Dec   Sat           349</span></span>
<span><span class="co">#&gt; 5 2022-05-29       1291.     11.8     103 20853  May   Sun           149</span></span>
<span><span class="co">#&gt; 6 2019-02-10       1392.     12.8       5 20700. Feb   Sun            41</span></span>
<span><span class="co">#&gt; # ℹ 486 more rows</span></span>
<span><span class="co">#&gt; # ℹ 1 more variable: stepgoal &lt;fct&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>is equivalent to:</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">fitness_df</span>, <span class="va">weekday</span> <span class="op">==</span> <span class="st">"Sat"</span> <span class="op">|</span> <span class="va">weekday</span> <span class="op">==</span> <span class="st">"Sun"</span><span class="op">)</span>,</span>
<span>        <span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">steps</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 492 × 9</span></span>
<span><span class="co">#&gt;   Start      active_cals distance flights  steps month weekday dayofyear</span></span>
<span><span class="co">#&gt;   &lt;date&gt;           &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 2023-07-15       2291.     18.0     193 32589. Jul   Sat           196</span></span>
<span><span class="co">#&gt; 2 2019-08-11       1385.     15.8     173 29480. Aug   Sun           223</span></span>
<span><span class="co">#&gt; 3 2019-04-14       1767.     17.9       1 25578  Apr   Sun           104</span></span>
<span><span class="co">#&gt; 4 2018-12-15       1091.     11.2      27 21224. Dec   Sat           349</span></span>
<span><span class="co">#&gt; 5 2022-05-29       1291.     11.8     103 20853  May   Sun           149</span></span>
<span><span class="co">#&gt; 6 2019-02-10       1392.     12.8       5 20700. Feb   Sun            41</span></span>
<span><span class="co">#&gt; # ℹ 486 more rows</span></span>
<span><span class="co">#&gt; # ℹ 1 more variable: stepgoal &lt;fct&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>So, why use the pipe? Compare the code the uses the pipe operator to the code that doesn’t. Which is easier to read? Which do you think is easier to write? The example shows that, for our purposes, the pipe is most useful in aiding the readability of our code. It’s a lot easier to see what’s happening in the code chunk with the pipes than it is in the previous code chunk without the pipe because, with the pipe, we can read the code from left to right and top to bottom. Without the pipe, we need to read the code from the “inside to the outside”, which is much more challenging.</p>
<p>There are many situations in which using the <code>|&gt;</code> would not be appropriate. To use the pipe, what precedes the <code>|&gt;</code> must be the first argument in the function following the <code>|&gt;</code>. For <code>tidyverse</code> functions that we use throughout the course, this condition is almost always true because these functions were designed with piping in mind. But, for non-<code>tidyverse</code> functions, this may not be the case.</p>
<p>For example, if you have taken STAT 213, you’ve used <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> to fit many different types of linear models. If you haven’t taken STAT 213, <code>lm(response ~ explanatory, data = name_of_data_set)</code> stands for “linear model” and can be used to fit the simple linear regression model that you learned about in STAT 113. You might expect something like this to fit a linear model using <code>fitness_df</code> with <code>active_cals</code> as the response and <code>steps</code> as the predictor:</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fitness_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">active_cals</span> <span class="op">~</span> <span class="va">steps</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in as.data.frame.default(data): cannot coerce class '"formula"' to a data.frame</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>But it throws us an error. Typing in <code><a href="https://rdrr.io/r/stats/lm.html">?lm</a></code> reveals that its first argument is a <code>formula</code> to fit the model, not a data set. So the function is trying to run</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">fitness_df</span>, <span class="va">active_cals</span> <span class="op">~</span> <span class="va">steps</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in as.data.frame.default(data): cannot coerce class '"formula"' to a data.frame</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>which doesn’t work because the arguments to the function are mixed up (the formula should appear first and the data set should appear second).</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The pipe operator <code>|&gt;</code> is relatively new. Previously, the primary pipe operator used was <code>%&gt;%</code> and came from the <code>magrittr</code> package. For almost all cases, the two operators are equivalent. However, when scanning the Internet for help with code, you will probably see <code>%&gt;%</code> used in many of people’s responses on sites like StackOverflow.</p>
</div>
</div>
<p><strong>Exercise 9</strong>. This “More About the Pipe” section will make more sense as we proceed through the course. For now, we just want to be able to understand that something like <code>df |&gt; slice(1:6)</code> is equivalent to <code>slice(df, 1:6)</code>. Practice by converting the following code to use the pipe:</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">fitness_df</span>, <span class="va">active_cals</span> <span class="op">&gt;</span> <span class="fl">50</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1,690 × 9</span></span>
<span><span class="co">#&gt;   Start      active_cals distance flights  steps month weekday dayofyear</span></span>
<span><span class="co">#&gt;   &lt;date&gt;           &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 2018-11-28        57.8    0.930       0  1885. Nov   Wed           332</span></span>
<span><span class="co">#&gt; 2 2018-11-29       509.     4.64       18  8953. Nov   Thu           333</span></span>
<span><span class="co">#&gt; 3 2018-11-30       599.     6.05       12 11665  Nov   Fri           334</span></span>
<span><span class="co">#&gt; 4 2018-12-01       661.     6.80        6 12117  Dec   Sat           335</span></span>
<span><span class="co">#&gt; 5 2018-12-02       527.     4.61        1  8925. Dec   Sun           336</span></span>
<span><span class="co">#&gt; 6 2018-12-03       550.     3.96        2  7205  Dec   Mon           337</span></span>
<span><span class="co">#&gt; # ℹ 1,684 more rows</span></span>
<span><span class="co">#&gt; # ℹ 1 more variable: stepgoal &lt;fct&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section id="practice" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="practice">
<span class="header-section-number">3.2</span> Practice</h2>
<p>In general, practice exercises will be split between exercises that will be done together as a class and exercises that you will do in groups or on your own. The purpose of the class exercises is to give some guidance on how we might think logically through some of the code and the results. The purpose of the group exercises and the on your own exercises is so that you have a chance to practice what you’ve learned with your table or on your own.</p>
<section id="class-exercises" class="level3" data-number="3.2.1"><h3 data-number="3.2.1" class="anchored" data-anchor-id="class-exercises">
<span class="header-section-number">3.2.1</span> Class Exercises</h3>
<p>For many of these class exercises, we will start practicing stringing together multiple piping statements. We will also practice more with <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code> by making plots of some of the data sets we are creating.</p>
<p><strong>Class Exercise 1</strong>. In the <code>babynames</code> data set, use <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code>, and <code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice()</a></code> to print the 10 most popular Male babynames in 2017.</p>
<p><strong>Class Exercise 2</strong>. Name the data frame you created in the previous exercise and use the data frame to make a bar plot of the 10 most popular Male babynames in 2017, along with the number of babies with each name in that year.</p>
<p><strong>Class Exercise 3</strong>. In the <code>babynames</code> data set, keep only the rows with your name (or, another name that interests you) and one sex (either <code>"M"</code> or <code>"F"</code>).</p>
<p><strong>Class Exercise 4</strong>. Name the new data set you made in the previous exercise and then construct a line plot that looks at either the <code>n</code> or <code>prop</code> of your chosen name through <code>year</code>.</p>
<p><strong>Class Exercise 5</strong>. Explain why the following code gives a warning message and returns <code>NA</code>. Use the order of Arguments in <code><a href="https://rdrr.io/r/base/mean.html">?mean</a></code> in your explanation.</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fitness_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">distance</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="your-turn" class="level3" data-number="3.2.2"><h3 data-number="3.2.2" class="anchored" data-anchor-id="your-turn">
<span class="header-section-number">3.2.2</span> Your Turn</h3>
<p><strong>Your Turn 1</strong>. Get a little more practice with using conditions in <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> by completing the following:</p>
<ol type="a">
<li><p>Create a data set with all years <strong>except</strong> the year 1945.</p></li>
<li><p>Create a data set that only has rows where <code>n</code> is between 400 and 5000.</p></li>
<li><p>Create a data set with rows that are either <code>F</code> (female) <code>Monica</code> names or <code>F</code> (female) <code>Hilary</code> names.</p></li>
</ol>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The syntax <code>filter(x_var &gt; 20 &amp; &lt; 30)</code> is not correct. The variable that we are filtering with needs to go in <strong>each</strong> conditional statement: <code>filter(x_var &gt; 20 &amp; x_var &lt; 30)</code></p>
</div>
</div>
</div>
<p><strong>Your Turn 2</strong>. Name your data set is part (c) of the previous exercise. Then, use the data set to make a line plot comparing the popularity of the <code>Monica</code> and <code>Hilary</code> names through time.</p>
<p><strong>Your Turn 3</strong>. Choose 5 names paired with 5 sexes that interest you and create a new data set that only has data on those 5 name/sex combinations. Then, make a line plot showing the popularity of these 5 names over time.</p>
<p><strong>Your Turn 4</strong>. Choose a year and a sex that interests you and create a data set that only contain observations from that year and sex. Then, make a bar plot that shows the top 10 names from that year and sex, showing the <code>prop</code> of babies born with each of those 10 names in that year.</p>
</section></section><section id="mutate-group_by-summarise-and-missing-values" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="mutate-group_by-summarise-and-missing-values">
<span class="header-section-number">3.3</span> <code>mutate()</code>, <code>group_by()</code>, <code>summarise()</code>, and Missing Values</h2>
<p><strong>Goals:</strong></p>
<ul>
<li>Use the <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else()</a></code>, and <code><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when()</a></code> functions to create new variables.</li>
<li>Use <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> to create useful summaries of a data set. * Explain what <code>dplyr</code> functions do with missing values.</li>
<li>Combine the above goals with plotting to explore a data set on SLU majors.</li>
</ul>
<p>Throughout this section, we will use a data set that contains observations for each of SLU’s majors, with three variables per major:</p>
<ul>
<li>
<code>Major</code>, the name of the major.</li>
<li>
<code>nfemales</code>, the number of female graduates in that major from 2017 - 2021.</li>
<li>
<code>nmales</code>, the number of male graduates in that major from 2017 - 2021.</li>
</ul>
<p>Begin by reading in the data set with</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="va">slumajors_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://raw.githubusercontent.com/highamm/ds234_quarto/main/data_online/SLU_Majors_17_21.csv"</span><span class="op">)</span></span>
<span><span class="va">slumajors_df</span></span>
<span><span class="co">#&gt; # A tibble: 30 × 3</span></span>
<span><span class="co">#&gt;   Major                        nfemales nmales</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;                           &lt;dbl&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 Anthropology                       35     13</span></span>
<span><span class="co">#&gt; 2 Art &amp; Art History                  62     11</span></span>
<span><span class="co">#&gt; 3 Biochemistry                       15      6</span></span>
<span><span class="co">#&gt; 4 Biology                           152     58</span></span>
<span><span class="co">#&gt; 5 Business in the Liberal Arts      192    301</span></span>
<span><span class="co">#&gt; 6 Chemistry                          28     20</span></span>
<span><span class="co">#&gt; # ℹ 24 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="mutate-create-variables" class="level3" data-number="3.3.1"><h3 data-number="3.3.1" class="anchored" data-anchor-id="mutate-create-variables">
<span class="header-section-number">3.3.1</span> <code>mutate()</code>: Create Variables</h3>
<p>Sometimes, we will want to create a new variable that’s not in the data set, oftentimes using <code><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when()</a></code>, or basic algebraic operations on one or more of the columns already present in the data set.</p>
<p><code>R</code> understands the following symbols:</p>
<ul>
<li>
<code>+</code> for addition, <code>-</code> for subtraction</li>
<li>
<code>*</code> for multiplication, <code>/</code> for division</li>
<li>
<code>^</code> for raising something to a power (<code>3 ^ 2</code> is equal to <code>9</code>)</li>
</ul>
<p><code>R</code> also does the same order of operations as usual: parentheses, then exponents, then multiplication and division, then addition and subtraction.</p>
<p>For example, suppose that we want to create a variable in <code>slumajors_df</code> that has the total number of students graduating in each major. We can do this with <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slumajors_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ntotal <span class="op">=</span> <span class="va">nfemales</span> <span class="op">+</span> <span class="va">nmales</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 30 × 4</span></span>
<span><span class="co">#&gt;   Major                        nfemales nmales ntotal</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;                           &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 Anthropology                       35     13     48</span></span>
<span><span class="co">#&gt; 2 Art &amp; Art History                  62     11     73</span></span>
<span><span class="co">#&gt; 3 Biochemistry                       15      6     21</span></span>
<span><span class="co">#&gt; 4 Biology                           152     58    210</span></span>
<span><span class="co">#&gt; 5 Business in the Liberal Arts      192    301    493</span></span>
<span><span class="co">#&gt; 6 Chemistry                          28     20     48</span></span>
<span><span class="co">#&gt; # ℹ 24 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>|&gt;</code> operator reads as “and then”, as in “take <code>slumajors_df</code> <em>and then</em> <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> it.”</p>
<p>Piping is a really convenient, easy-to-read way to build a sequence of commands. How you can read the above code is:</p>
<ol type="1">
<li><p>Take <code>slumajors_df</code> and with <code>slumajors_df</code>,</p></li>
<li><p>perform a <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> step to create the new variable called <code>ntotal</code>, which is <code>nfemales</code> plus <code>nmales</code>.</p></li>
</ol>
<p>Since this is our first time using <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>, let’s also delve into what the function is doing. In general, <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> reads:</p>
<p><code>mutate(name_of_new_variable = operations_on_old_variables)</code>.</p>
<p><code>R</code> just automatically assumes that you want to do the operation for every single row in the data set, which is often quite convenient!</p>
<p>We might also want to create a variable that is the percentage of students identifying as female for each major:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slumajors_df</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>percfemale <span class="op">=</span> <span class="fl">100</span> <span class="op">*</span> <span class="va">nfemales</span> <span class="op">/</span> <span class="op">(</span><span class="va">nfemales</span> <span class="op">+</span> <span class="va">nmales</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 30 × 4</span></span>
<span><span class="co">#&gt;   Major                        nfemales nmales percfemale</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;                           &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 Anthropology                       35     13       72.9</span></span>
<span><span class="co">#&gt; 2 Art &amp; Art History                  62     11       84.9</span></span>
<span><span class="co">#&gt; 3 Biochemistry                       15      6       71.4</span></span>
<span><span class="co">#&gt; 4 Biology                           152     58       72.4</span></span>
<span><span class="co">#&gt; 5 Business in the Liberal Arts      192    301       38.9</span></span>
<span><span class="co">#&gt; 6 Chemistry                          28     20       58.3</span></span>
<span><span class="co">#&gt; # ℹ 24 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>What happened to <code>ntotal</code>? Is it still in the printout? It’s not: when we created the variable <code>ntotal</code>, we didn’t actually <strong>save</strong> (or assign a name to) the new data set as anything. So <code>R</code> makes and prints the new variable, but it doesn’t get saved to any data set.</p>
</div>
</div>
<p>If we want to save the new data set for later use, then we can use the <code>&lt;-</code> operator. Here, we’re naming the new data set with the same name as the old data set: <code>slumajors_df</code>. Then, we’re doing the same thing for the <code>percfemale</code> variable. We won’t always want to give the new data set the same name as the old one: we’ll talk about this in more detail in the class exercises.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slumajors_df</span> <span class="op">&lt;-</span> <span class="va">slumajors_df</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>percfemale <span class="op">=</span> <span class="fl">100</span> <span class="op">*</span> <span class="va">nfemales</span> <span class="op">/</span> <span class="op">(</span><span class="va">nfemales</span> <span class="op">+</span> <span class="va">nmales</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slumajors_df</span> <span class="op">&lt;-</span> <span class="va">slumajors_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ntotal <span class="op">=</span> <span class="va">nfemales</span> <span class="op">+</span> <span class="va">nmales</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>But, you can pipe as many things together as you want to, so it’s probably easier to just create both variables in one go. The following chunk says to “Take <code>slumajors_df</code> and create a new variable <code>ntotal</code>. With that new data set, create a new variable called <code>percfemale</code>.” Finally, the <code>slumajors_df &lt;-</code> at the beginning says to “save this new data set as a data set with the same name, <code>slumajors_df</code>, thus overwriting the original <code>slumajors_df</code>.”</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slumajors_df</span> <span class="op">&lt;-</span> <span class="va">slumajors_df</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ntotal <span class="op">=</span> <span class="va">nfemales</span> <span class="op">+</span> <span class="va">nmales</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>percfemale <span class="op">=</span> <span class="fl">100</span> <span class="op">*</span> <span class="va">nfemales</span> <span class="op">/</span> <span class="op">(</span><span class="va">nfemales</span> <span class="op">+</span> <span class="va">nmales</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now suppose that you want to make a new variable that is conditional on another variable (or more than one variable) in the data set. Then we would typically use <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> coupled with</p>
<ul>
<li>
<code><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else()</a></code> if your new variable is created on only one condition</li>
<li>
<code><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when()</a></code> if your new variable is created on more than one condition</li>
</ul>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The conditions that we supply use the same syntax as the conditions we used with <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>. For example, we still use the same Boolean operators (<code>&amp;</code> for “and” and <code>|</code> for “or”, etc.).</p>
</div>
</div>
<p>Suppose we want to create a new variable that tells us whether or not the <code>Major</code> has a majority of Women. That is, we want this new variable, <code>morewomen</code> to be <code>"Yes"</code> if the <code>Major</code> has more than 50% women and <code>"No"</code> if it has 50% or less.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slumajors_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>morewomen <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">percfemale</span> <span class="op">&gt;</span> <span class="fl">50</span>,</span>
<span>                                            true <span class="op">=</span> <span class="st">"Yes"</span>,</span>
<span>                                            false <span class="op">=</span> <span class="st">"No"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 30 × 6</span></span>
<span><span class="co">#&gt;   Major                        nfemales nmales percfemale ntotal morewomen</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;                           &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    </span></span>
<span><span class="co">#&gt; 1 Anthropology                       35     13       72.9     48 Yes      </span></span>
<span><span class="co">#&gt; 2 Art &amp; Art History                  62     11       84.9     73 Yes      </span></span>
<span><span class="co">#&gt; 3 Biochemistry                       15      6       71.4     21 Yes      </span></span>
<span><span class="co">#&gt; 4 Biology                           152     58       72.4    210 Yes      </span></span>
<span><span class="co">#&gt; 5 Business in the Liberal Arts      192    301       38.9    493 No       </span></span>
<span><span class="co">#&gt; 6 Chemistry                          28     20       58.3     48 Yes      </span></span>
<span><span class="co">#&gt; # ℹ 24 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> statement reads: create a new variable called <code>morewomen</code> that is equal to <code>"Yes"</code> if <code>percfemale</code> &gt; <code>50</code> is true and is equal to <code>"No"</code> if <code>perfemale</code> is not &gt; <code>0.5</code>. The first argument is the condition, the second is what to name the new variable when the condition holds, and the third is what to name the variable if the condition does not hold.</p>
<p>We use <strong>conditions</strong> all of the time in every day life. For example, New York had a quarantine order stating that people coming from 22 states in July 2020 would need to quarantine. In terms of a condition, this would read “if you are traveling to New York from one of the 22 states, then you need to quarantine for 2 weeks. Else, if not, then you don’t need to quarantine.” The trick in using these conditions in <code>R</code> is getting used to the syntax of the code.</p>
<p>We can see from the above set up that if we had more than one condition, then we’d need to use a different function (or use nested <code><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else()</a></code> statements, which can be a nightmare to read). If we have more than one condition for creating the new variable, we will use <code><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when()</a></code>.</p>
<p>For example, when looking at the output, we see that <code>Biochemistry</code> has 56% female graduates. That’s “about” a 50/50 split, so suppose we want a variable called <code>large_majority</code> that is <code>"female"</code> when the percent women is 70 or more, <code>"male"</code> when the percent women is 30 or less, and <code>"none"</code> when the percent female is between 30 and 70.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slumajors_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>large_majority <span class="op">=</span></span>
<span>                          <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span><span class="va">percfemale</span> <span class="op">&gt;=</span> <span class="fl">70</span> <span class="op">~</span> <span class="st">"female"</span>,</span>
<span>                                    <span class="va">percfemale</span> <span class="op">&lt;=</span> <span class="fl">30</span> <span class="op">~</span> <span class="st">"male"</span>,</span>
<span>                                    <span class="va">percfemale</span> <span class="op">&gt;</span> <span class="fl">30</span> <span class="op">&amp;</span> <span class="va">percfemale</span> <span class="op">&lt;</span> <span class="fl">70</span> <span class="op">~</span> <span class="st">"none"</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="co">#&gt; # A tibble: 30 × 6</span></span>
<span><span class="co">#&gt;   Major                      nfemales nmales percfemale ntotal large_majority</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;                         &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;         </span></span>
<span><span class="co">#&gt; 1 Anthropology                     35     13       72.9     48 female        </span></span>
<span><span class="co">#&gt; 2 Art &amp; Art History                62     11       84.9     73 female        </span></span>
<span><span class="co">#&gt; 3 Biochemistry                     15      6       71.4     21 female        </span></span>
<span><span class="co">#&gt; 4 Biology                         152     58       72.4    210 female        </span></span>
<span><span class="co">#&gt; 5 Business in the Liberal A…      192    301       38.9    493 none          </span></span>
<span><span class="co">#&gt; 6 Chemistry                        28     20       58.3     48 none          </span></span>
<span><span class="co">#&gt; # ℹ 24 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when()</a></code> function reads “When the percent female is more than or equal to 70, assign the new variable <code>large_majority</code> the value of <code>"female"</code>, when it’s less or equal to 30, assign the new variable <code>large_majority</code> the value of <code>"male"</code>, and when it’s more than 30 and less than 70, assign the <code>large_majority</code> variable the value of <code>"none"</code>.</p>
<p>Let’s save these two new variables to the <code>slumajors_df</code>:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slumajors_df</span> <span class="op">&lt;-</span> <span class="va">slumajors_df</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>morewomen <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">percfemale</span> <span class="op">&gt;</span> <span class="fl">50</span>,</span>
<span>                             true <span class="op">=</span> <span class="st">"Yes"</span>,</span>
<span>                             false <span class="op">=</span> <span class="st">"No"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>large_majority <span class="op">=</span></span>
<span>           <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span><span class="va">percfemale</span> <span class="op">&gt;=</span> <span class="fl">70</span> <span class="op">~</span> <span class="st">"female"</span>,</span>
<span>                     <span class="va">percfemale</span> <span class="op">&lt;=</span> <span class="fl">30</span> <span class="op">~</span> <span class="st">"male"</span>,</span>
<span>                     <span class="va">percfemale</span> <span class="op">&gt;</span> <span class="fl">30</span> <span class="op">&amp;</span> <span class="va">percfemale</span> <span class="op">&lt;</span> <span class="fl">70</span> <span class="op">~</span> <span class="st">"none"</span><span class="op">)</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Numeric values typically do not go in quotation marks (like <code>70</code> and <code>30</code>) while strings like <code>"female"</code> and <code>"none"</code> do need quotes.</p>
</div>
</div>
<p><strong>Exercise 1</strong>. Use <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> with <code><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else()</a></code> to create a new variable that is called <code>major_size</code> and is equal to <code>"large"</code> when the total number of majors is 100 or more and <code>"small"</code> when the total number of majors is less than 100.</p>
<p><strong>Exercise 2</strong>. Use <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> with <code><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when()</a></code> to create a new variable that is called <code>major_size2</code> and is <code>"large"</code> when the total number of majors is 150 or more, <code>"medium"</code> when the total number of majors is between 41 and 149, and <code>"small"</code> when the total number of majors is 40 or fewer.</p>
<p><strong>Exercise 3</strong>. Create a new variable that is the <code>nfemales</code> to <code>nmales</code> ratio (so your new variable should be <code>nfemales</code> divided by <code>nmales</code>).</p>
</section><section id="summarise-create-summaries" class="level3" data-number="3.3.2"><h3 data-number="3.3.2" class="anchored" data-anchor-id="summarise-create-summaries">
<span class="header-section-number">3.3.2</span> <code>summarise()</code>: Create Summaries</h3>
<p>The <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> function is useful to get various summaries from the data. For example, suppose that we want to know the average major size at SLU across the five year span or the total number of majors across those five years. Then we can use <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> and a summary function, like <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>, <code><a href="https://rdrr.io/r/base/sum.html">sum()</a></code>, <code><a href="https://rdrr.io/r/stats/median.html">median()</a></code>, <code><a href="https://rdrr.io/r/base/Extremes.html">max()</a></code>, <code><a href="https://rdrr.io/r/base/Extremes.html">min()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/context.html">n()</a></code>, etc. You’ll notice that the format of <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> is extremely similar to the format of <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>. Using the <code>slumajors_df</code> data again just for one quick example,</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slumajors_df</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>meantotalmajor <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ntotal</span><span class="op">)</span>,</span>
<span>            totalgrad <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">ntotal</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 2</span></span>
<span><span class="co">#&gt;   meantotalmajor totalgrad</span></span>
<span><span class="co">#&gt;            &lt;dbl&gt;     &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1           117.      3502</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the code chunk above, we obtain two summaries (<code>meantotalmajor</code> and <code>totalgrad</code>), separated by a comma. In general, this syntax also works with <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> to create more than one variable in the same <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> function.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Most summary functions are intuitive if you’ve had intro stat. But, if you’re not sure whether the summary for getting the maximum is <code>maximum()</code> or <code><a href="https://rdrr.io/r/base/Extremes.html">max()</a></code>, just try both or do a quick google search.</p>
</div>
</div>
<p>Another useful summary function is <code><a href="https://dplyr.tidyverse.org/reference/context.html">n()</a></code>, the counting function, which counts up the total number of rows.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slumajors_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>totalobs <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 1</span></span>
<span><span class="co">#&gt;   totalobs</span></span>
<span><span class="co">#&gt;      &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1       30</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The counting function <code><a href="https://dplyr.tidyverse.org/reference/context.html">n()</a></code> typically doesn’t have any arguments. It’s typically more useful when paired with <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code>, which is discussed next.</p>
</div>
</div>
<p><strong>Exercise 4</strong>. Find the total number of <code>nfemales</code> in the data set and the total number of <code>nmales</code> in the data set.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint (only if you get stuck)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The summary function you will need to use within <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> is <code><a href="https://rdrr.io/r/base/sum.html">sum()</a></code>, which will add up the numbers in the <code>nfemales</code> column. You’ll then need to add a <code>,</code> and then <code><a href="https://rdrr.io/r/base/sum.html">sum()</a></code> the number of <code>nmales</code>.</p>
</div>
</div>
</div>
</section><section id="group_by-groups" class="level3" data-number="3.3.3"><h3 data-number="3.3.3" class="anchored" data-anchor-id="group_by-groups">
<span class="header-section-number">3.3.3</span> <code>group_by()</code>: Groups</h3>
<p><code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> is often most useful when paired with a <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> statement. Doing so allows us to get summaries across different groups. Conceptually, we can think of <code>toy_df |&gt; group_by(categorical_var)</code> as “grouping” <code>toy_df</code> into a bunch of different groups, with one group for each level of <code>categorical_var</code>. Then, operations from any other functions after the <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> function are carried out <strong>for each group</strong>.</p>
<p>For example, suppose that you wanted the total number of registered births per year in the <code>babynames</code> data set that we used earlier. We can then use <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> to “split” the <code>babynames</code> data frame into 138 separate data frames (one for each <code>year</code> in the data set). After we <code>group_by(year)</code>, then the <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> statement below adds up the <code>n</code> variable for each <code>year</code>:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>totalbirths <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 138 × 2</span></span>
<span><span class="co">#&gt;    year totalbirths</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt;       &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1  1880      201484</span></span>
<span><span class="co">#&gt; 2  1881      192696</span></span>
<span><span class="co">#&gt; 3  1882      221533</span></span>
<span><span class="co">#&gt; 4  1883      216946</span></span>
<span><span class="co">#&gt; 5  1884      243462</span></span>
<span><span class="co">#&gt; 6  1885      240854</span></span>
<span><span class="co">#&gt; # ℹ 132 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As another example, we can also use the <code><a href="https://dplyr.tidyverse.org/reference/context.html">n()</a></code> function to count up the number of rows for each <code>year</code>:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>n_name <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 138 × 2</span></span>
<span><span class="co">#&gt;    year n_name</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt;  &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1  1880   2000</span></span>
<span><span class="co">#&gt; 2  1881   1935</span></span>
<span><span class="co">#&gt; 3  1882   2127</span></span>
<span><span class="co">#&gt; 4  1883   2084</span></span>
<span><span class="co">#&gt; 5  1884   2297</span></span>
<span><span class="co">#&gt; 6  1885   2294</span></span>
<span><span class="co">#&gt; # ℹ 132 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> can be used in combination with the other <code>dplyr</code> functions we have learned about (<code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>, etc.). We will explore this functionality in class.</p>
</div>
</div>
<p><strong>Exercise 5</strong>. With the <code>babynames</code> data set, use <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> to create a data set that has the total number of births for each <code>name</code>.</p>
<p><strong>Exercise 6</strong>. With the <code>babynames</code> data set, use <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> to create a data set that has how many times each <code>name</code> appears in <code>babynames</code>.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint (only if you get stuck)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For one of the previous exercises, you will need to use the <code><a href="https://rdrr.io/r/base/sum.html">sum()</a></code> function on <code>n</code>, the column with the total number of births while for the other exercise, you will need to use the <code><a href="https://dplyr.tidyverse.org/reference/context.html">n()</a></code> function.</p>
</div>
</div>
</div>
</section><section id="missing-values" class="level3" data-number="3.3.4"><h3 data-number="3.3.4" class="anchored" data-anchor-id="missing-values">
<span class="header-section-number">3.3.4</span> Missing Values</h3>
<p>Both of the data sets that we’ve worked with are nice in that they do not have any missing values. We’ll see plenty of examples of data sets with missing values later, so we should examine how the various functions that we’ve talked about so far tackle missing values.</p>
<p>Missing values in <code>R</code> are denoted with <code>NA</code> for “Not Available.” Run the following code to create a toy data set with some missing values so that we can see how the various functions we’ve used so far deal with <code>NA</code> values.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">toy_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="cn">NA</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">7</span><span class="op">)</span>,</span>
<span>                 y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">4</span>, <span class="fl">3</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>                 z <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"A"</span>, <span class="st">"A"</span>, <span class="st">"B"</span>, <span class="cn">NA</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">toy_df</span></span>
<span><span class="co">#&gt; # A tibble: 4 × 3</span></span>
<span><span class="co">#&gt;       x     y z    </span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;</span></span>
<span><span class="co">#&gt; 1    NA     1 A    </span></span>
<span><span class="co">#&gt; 2     3     4 A    </span></span>
<span><span class="co">#&gt; 3     4     3 B    </span></span>
<span><span class="co">#&gt; 4     7     2 &lt;NA&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will first discuss how to remove missing values when computing summaries for a variable that contains some <code>NA</code> values.</p>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Missing values should not be removed without carefully examination and a note of what the consequences might be (i.e.&nbsp;why are these values missing?).</p>
</div>
</div>
<p>We have a toy data set that is meaningless, so we aren’t asking those questions now, but we will for any future data set that does have missing values!</p>
<p><strong>If</strong> we have investigated the missing values and are comfortable with removing them, many functions that we would use in <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> have an <code>na.rm</code> argument that we can set to <code>TRUE</code> to tell <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> to remove any <code>NA</code>s before taking the <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>, <code><a href="https://rdrr.io/r/stats/median.html">median()</a></code>, <code><a href="https://rdrr.io/r/base/Extremes.html">max()</a></code>, etc.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">toy_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>meanx <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">x</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 1</span></span>
<span><span class="co">#&gt;   meanx</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  4.67</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we want to remove the missing values more directly, we can use the <code><a href="https://rdrr.io/r/base/NA.html">is.na()</a></code> function in combination with <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>. If the variable is <code>NA</code> (Not Available) for an observation, <code><a href="https://rdrr.io/r/base/NA.html">is.na()</a></code> evaluates to <code>TRUE</code>; if not, <code><a href="https://rdrr.io/r/base/NA.html">is.na()</a></code> evaluates to <code>FALSE</code>. Test this out using <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> to create a new variable for whether <code>x</code> is missing:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">toy_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>missingx <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 4 × 4</span></span>
<span><span class="co">#&gt;       x     y z     missingx</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;lgl&gt;   </span></span>
<span><span class="co">#&gt; 1    NA     1 A     TRUE    </span></span>
<span><span class="co">#&gt; 2     3     4 A     FALSE   </span></span>
<span><span class="co">#&gt; 3     4     3 B     FALSE   </span></span>
<span><span class="co">#&gt; 4     7     2 &lt;NA&gt;  FALSE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>missingx</code> is <code>TRUE</code> only for the the first observation. We can use this to our advantage with <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> to filter it out of the data set, without going through the extra step of actually making a new variable <code>missingx</code>:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">toy_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">!=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 3</span></span>
<span><span class="co">#&gt;       x     y z    </span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;</span></span>
<span><span class="co">#&gt; 1     3     4 A    </span></span>
<span><span class="co">#&gt; 2     4     3 B    </span></span>
<span><span class="co">#&gt; 3     7     2 &lt;NA&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You’ll commonly see this written as short-hand in people’s code you may come across as:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">toy_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 3</span></span>
<span><span class="co">#&gt;       x     y z    </span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;</span></span>
<span><span class="co">#&gt; 1     3     4 A    </span></span>
<span><span class="co">#&gt; 2     4     3 B    </span></span>
<span><span class="co">#&gt; 3     7     2 &lt;NA&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>which says to “keep anything that does not have a missing <code>x</code> value” (recall that the <code>!</code> means “not” so that we are filtering to keep any value of <code>x</code> that is “not” missing).</p>
<p><strong>Exercise 7</strong>. <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> <code>toy_df</code> to keep only the rows where <code>z</code> is not missing.</p>
</section></section><section id="practice-1" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="practice-1">
<span class="header-section-number">3.4</span> Practice</h2>
<p>In general, practice exercises will be split between exercises that will be done together as a class and exercises that you will do in groups or on your own. The purpose of the class exercises is to give some guidance on how we might think logically through some of the code and the results. The purpose of the group exercises and the on your own exercises is so that you have a chance to practice what you’ve learned with your table or on your own.</p>
<section id="class-exercises-1" class="level3" data-number="3.4.1"><h3 data-number="3.4.1" class="anchored" data-anchor-id="class-exercises-1">
<span class="header-section-number">3.4.1</span> Class Exercises</h3>
<p><strong>Class Exercise 1</strong>. About 55% of SLU students identify as female. So, in the definition of the <code>morewomen</code> variable, does it make more sense to use 55% as the cutoff or 50%?</p>
<p><strong>Class Exercise 2</strong>. Do you think it is ethical to exclude non-binary genders from analyses and graphs in the <code>slumajors</code> data set? What about in the <code>stat113_df</code> data that we looked at earlier? Why or why not? Try to construct arguments for both sides: you might also consider data privacy in your arguments.</p>
<p><strong>Class Exercise 3</strong>. Investigate what happens with <code><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when()</a></code> when you give overlapping conditions and when you give conditions that don’t cover all observations. For overlapping conditions, create a variable <code>testcase</code> that is <code>"Yes"</code> when <code>percfemale</code> is greater than or equal to 40 and <code>"No"</code> when <code>percfemale</code> is greater than 60 For conditions that don’t cover all observations, create a variable <code>testcase2</code> that is <code>"Yes"</code> when <code>percfemale</code> is greater than or equal to 55 and <code>"No"</code> when <code>percfemale</code> is less than 35. Put the new variables at the beginning of the data frame so that you can see what they contain more easily.</p>
<p><strong>Class Exercise 4</strong>. The <code><a href="https://rdrr.io/r/base/rank.html">rank()</a></code> function can be used within <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> to “rank” a variable from lowest values to highest values (so that the case with the lowest value receives a <code>1</code>, the second lowest value receives a <code>2</code>, etc.). Use <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> to rank the names from most to least popular in each year-sex combination. We will make some notes about what <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> does with more than 1 variable.</p>
<p><strong>Class Exercise 5</strong>. From the data set in the previous exercise, <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> the data to keep only the most popular name in each year-sex combination and then construct a summary table showing how many times each name appears as the most popular name. With this exercise, we will make some notes about the <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup()</a></code> function, and, if we have time investigate a way to achieve the objective of this question without explicitly making a <code>rank</code> variable.</p>
<p><strong>Class Exercise 6</strong>. Run the following code. Intuitively, a <code>slice(1, 2, 3, 4, 5)</code> should grab the first five rows of the data set, but, when we try to run that, we get 1380 rows. What is the issue?</p>
<div class="cell">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">babynames_test</span> <span class="op">&lt;-</span> <span class="va">babynames</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">year</span>, <span class="va">sex</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ntest <span class="op">=</span> <span class="va">n</span> <span class="op">/</span> <span class="va">prop</span><span class="op">)</span></span>
<span><span class="va">babynames_test</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">5</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1,380 × 6</span></span>
<span><span class="co">#&gt; # Groups:   year, sex [276]</span></span>
<span><span class="co">#&gt;    year sex   name          n   prop   ntest</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;   &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  1880 F     Mary       7065 0.0724  97605.</span></span>
<span><span class="co">#&gt; 2  1880 F     Anna       2604 0.0267  97605.</span></span>
<span><span class="co">#&gt; 3  1880 F     Emma       2003 0.0205  97605.</span></span>
<span><span class="co">#&gt; 4  1880 F     Elizabeth  1939 0.0199  97605.</span></span>
<span><span class="co">#&gt; 5  1880 F     Minnie     1746 0.0179  97605.</span></span>
<span><span class="co">#&gt; 6  1880 M     John       9655 0.0815 118400.</span></span>
<span><span class="co">#&gt; # ℹ 1,374 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="your-turn-1" class="level3" data-number="3.4.2"><h3 data-number="3.4.2" class="anchored" data-anchor-id="your-turn-1">
<span class="header-section-number">3.4.2</span> Your Turn</h3>
<p><strong>Your Turn 1</strong>. Investigate how <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> behaves with the five other main <code>dplyr</code> functions we have used. You can use <code>toy_df</code> to perform your investigation.</p>
<ol type="a">
<li><p><code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code></p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice()</a></code></p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code></p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code></p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code></p></li>
</ol>
<p><strong>Your Turn 2</strong>. Use <code>toy_df</code> again to investigate how the <code>dplyr</code> functions treat missing values by default.</p>
<ol type="a">
<li><p><code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>. Try to create a new variable with <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> involving <code>x</code>. What does <code>R</code> do with the missing value?</p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code>. Try arranging the data set by <code>x</code>. What does <code>R</code> do with the missing value?</p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>. Try filtering so that only observations where x is less than 5 are kept. What does <code>R</code> do with the missing value?</p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code>. Try using <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> with a function involving x. What does <code>R</code> return?</p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code>. To your statement in 4, add a <code>group_by(z)</code> statement before your <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code>. What does <code>R</code> return now?</p></li>
</ol>
<p><strong>Your Turn 3</strong>. In some cases throughout this chapter, we’ve renamed data sets using <code>&lt;-</code> with the same name like</p>
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">toy_df</span> <span class="op">&lt;-</span> <span class="va">toy_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>newvar <span class="op">=</span> <span class="va">x</span> <span class="op">/</span> <span class="va">y</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In other cases, we’ve given the data set a new name, like</p>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">toy_small</span> <span class="op">&lt;-</span> <span class="va">toy_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For which of the functions below is a generally “safe” to name the data set using the same name after using the function. Give a one sentence reason for each part.</p>
<ol type="a">
<li><p><code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code></p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code></p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code></p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code></p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code></p></li>
</ol>
<p><strong>Your Turn 4</strong>. Compare <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> with <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> using the following code. What’s the difference between the two functions?</p>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slumajors_df</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>meantotalmajor <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ntotal</span><span class="op">)</span>,</span>
<span>            totalgrad <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">ntotal</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="va">slumajors_df</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>meantotalmajor <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ntotal</span><span class="op">)</span>,</span>
<span>            totalgrad <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">ntotal</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">meantotalmajor</span>, <span class="va">totalgrad</span>, <span class="fu"><a href="https://tidyselect.r-lib.org/reference/everything.html">everything</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Your Turn 5</strong>. With the <code>babynames</code> data, create a data set that has the number of unique names for each year. Then, make a line plot of the data.</p>
<p><strong>Your Turn 6</strong>. With the <code>babynames</code> data, create a data set that has the number of unique names for each year-sex combination. Then, make a line plot of the data.</p>
<p><strong>Your Turn 7</strong>. Create a data set that has a column for <code>name</code> so that each row shows the total number of births for each unique name across all years and both sexes.</p>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./02-ggplot2.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Plotting with <code>ggplot2</code></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-comm.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Communication with <code>Quarto</code></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Course Materials were written by Matt Higham for STAT/DATA 234 at St.&nbsp;Lawrence University.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>