<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DATA / STAT 234 - 15&nbsp; Connections to STAT 113, STAT 213, and CS 140</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./16-sql.html" rel="next">
<link href="./13-knn.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Connections to STAT 113, STAT 213, and CS 140</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DATA / STAT 234</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle sidebar-tool" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Syllabus and Course Information</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">The Core</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with <code>R</code> and <code>R Studio</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Plotting with <code>ggplot2</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-dplyr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Wrangling with <code>dplyr</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-comm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Communication with <code>Quarto</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Workflow and Other Skills</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Data Wrangling</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-tidyr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tidying with <code>tidyr</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Coding in Base <code>R</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-forcats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Factors with <code>forcats</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-ethics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Data Ethics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-import.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data Import</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-merging.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Merging with <code>dplyr</code></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Special Topics</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-lubridate.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Dates with <code>lubridate</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-stringr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Text Data with <code>tidytext</code> and <code>stringr</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-knn.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Predictive Modeling with knn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-connections.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Connections to STAT 113, STAT 213, and CS 140</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-sql.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Introduction to SQL with <code>dbplyr</code></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#stat-113" id="toc-stat-113" class="nav-link active" data-scroll-target="#stat-113"> <span class="header-section-number">15.1</span> STAT 113</a>
  <ul class="collapse">
  <li><a href="#chi-square-test-of-association" id="toc-chi-square-test-of-association" class="nav-link" data-scroll-target="#chi-square-test-of-association"> <span class="header-section-number">15.1.1</span> Chi-square Test of Association</a></li>
  <li><a href="#additional-analysis" id="toc-additional-analysis" class="nav-link" data-scroll-target="#additional-analysis"> <span class="header-section-number">15.1.2</span> Additional Analysis</a></li>
  <li><a href="#exercise-15-1" id="toc-exercise-15-1" class="nav-link" data-scroll-target="#exercise-15-1"> <span class="header-section-number">15.1.3</span> Exercises</a></li>
  </ul></li>
  <li><a href="#stat-213" id="toc-stat-213" class="nav-link" data-scroll-target="#stat-213"> <span class="header-section-number">15.2</span> STAT 213</a>
  <ul class="collapse">
  <li><a href="#broom-package-functions" id="toc-broom-package-functions" class="nav-link" data-scroll-target="#broom-package-functions"> <span class="header-section-number">15.2.1</span> <code>broom</code> Package Functions</a></li>
  <li><a href="#exploring-concepts" id="toc-exploring-concepts" class="nav-link" data-scroll-target="#exploring-concepts"> <span class="header-section-number">15.2.2</span> Exploring Concepts</a></li>
  <li><a href="#exercise-15-2" id="toc-exercise-15-2" class="nav-link" data-scroll-target="#exercise-15-2"> <span class="header-section-number">15.2.3</span> Exercises</a></li>
  </ul></li>
  <li><a href="#cs-140" id="toc-cs-140" class="nav-link" data-scroll-target="#cs-140"> <span class="header-section-number">15.3</span> CS 140</a>
  <ul class="collapse">
  <li><a href="#functions" id="toc-functions" class="nav-link" data-scroll-target="#functions"> <span class="header-section-number">15.3.1</span> Functions</a></li>
  <li><a href="#iteration" id="toc-iteration" class="nav-link" data-scroll-target="#iteration"> <span class="header-section-number">15.3.2</span> Iteration</a></li>
  <li><a href="#exercise-15-3" id="toc-exercise-15-3" class="nav-link" data-scroll-target="#exercise-15-3"> <span class="header-section-number">15.3.3</span> Exercises</a></li>
  </ul></li>
  <li><a href="#chapexercise-15" id="toc-chapexercise-15" class="nav-link" data-scroll-target="#chapexercise-15"> <span class="header-section-number">15.4</span> Chapter Exercises</a></li>
  <li><a href="#solutions-15" id="toc-solutions-15" class="nav-link" data-scroll-target="#solutions-15"> <span class="header-section-number">15.5</span> Exercise Solutions</a>
  <ul class="collapse">
  <li><a href="#stat-113-s" id="toc-stat-113-s" class="nav-link" data-scroll-target="#stat-113-s"> <span class="header-section-number">15.5.1</span> STAT 113 S</a></li>
  <li><a href="#stat-213-s" id="toc-stat-213-s" class="nav-link" data-scroll-target="#stat-213-s"> <span class="header-section-number">15.5.2</span> STAT 213 S</a></li>
  <li><a href="#cs-140-s" id="toc-cs-140-s" class="nav-link" data-scroll-target="#cs-140-s"> <span class="header-section-number">15.5.3</span> CS 140 S</a></li>
  </ul></li>
  <li><a href="#rcode-15" id="toc-rcode-15" class="nav-link" data-scroll-target="#rcode-15"> <span class="header-section-number">15.6</span> Non-Exercise <code>R</code> Code</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="connections" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Connections to STAT 113, STAT 213, and CS 140</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="stat-113" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="stat-113"><span class="header-section-number">15.1</span> STAT 113</h2>
<p>In this section, we discuss how what we have learned in this data science course connects to some concepts that you learned about in STAT 113. As a quick refresher, a few concepts that you learned about in STAT 113 are:</p>
<ul>
<li>exploring data through numerical and graphical summaries. The connection to what we have been doing in this class is fairly straightforward: we’ve learned a lot about how to actually compute those numerical summaries and make appropriate graphics for potentially messy data.</li>
<li>explaining what sampling distributions are and how they relate to confidence intervals and hypothesis tests. This topic is probably the least connected to what we have learned so far in this class.</li>
<li>conducting hypothesis tests and creating confidence intervals to answer questions of interest. We will focus on this third general objective in this section.</li>
</ul>
<p>The example we will use is an experiment designed to assess the effects of race and sex on whether or not an employee received a callback for a job. In order to conduct the experiment, researchers randomly assigned names to resumes with each name associated with a particular race and gender, sent the resumes to employers, and recorded whether or not the resume received a callback. In addition to race, sex, and whether or not an employee received a callback, a few more variables were collected, like resume quality, whether or not the applicant had computer skills, years of experience, etc. A <code>1</code> for the <code>received_callback</code> indicates that the applicant received a callback.</p>
<p>You may recall this example from STAT 113: we used it to introduce a chi-square test of association. In that example and others like it, an appropriate graphic and summary statistics were provided. Here, we create these ourselves.</p>
<p>The data set is called <code>resume</code> in the <code>openintro</code> package: you’ll need to install this package with <code>install.packages("openintro")</code>. Then, load in the data with</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(openintro)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: airports</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: cherryblossom</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: usdata</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>resume</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,870 × 30
   job_ad_id job_city job_indu…¹ job_t…² job_f…³ job_e…⁴ job_o…⁵ job_r…⁶ job_r…⁷
       &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;      &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;
 1       384 Chicago  manufactu… superv…      NA       1 unknown       1       0
 2       384 Chicago  manufactu… superv…      NA       1 unknown       1       0
 3       384 Chicago  manufactu… superv…      NA       1 unknown       1       0
 4       384 Chicago  manufactu… superv…      NA       1 unknown       1       0
 5       385 Chicago  other_ser… secret…       0       1 nonpro…       1       0
 6       386 Chicago  wholesale… sales_…       0       1 private       0       0
 7       386 Chicago  wholesale… sales_…       0       1 private       0       0
 8       385 Chicago  other_ser… secret…       0       1 nonpro…       1       0
 9       386 Chicago  wholesale… sales_…       0       1 private       0       0
10       386 Chicago  wholesale… sales_…       0       1 private       0       0
# … with 4,860 more rows, 21 more variables: job_req_education &lt;dbl&gt;,
#   job_req_min_experience &lt;chr&gt;, job_req_computer &lt;dbl&gt;,
#   job_req_organization &lt;dbl&gt;, job_req_school &lt;chr&gt;, received_callback &lt;dbl&gt;,
#   firstname &lt;chr&gt;, race &lt;chr&gt;, gender &lt;chr&gt;, years_college &lt;int&gt;,
#   college_degree &lt;dbl&gt;, honors &lt;int&gt;, worked_during_school &lt;int&gt;,
#   years_experience &lt;int&gt;, computer_skills &lt;int&gt;, special_skills &lt;int&gt;,
#   volunteer &lt;int&gt;, military &lt;int&gt;, employment_holes &lt;int&gt;, …</code></pre>
</div>
</div>
<section id="chi-square-test-of-association" class="level3" data-number="15.1.1">
<h3 data-number="15.1.1" class="anchored" data-anchor-id="chi-square-test-of-association"><span class="header-section-number">15.1.1</span> Chi-square Test of Association</h3>
<p>Our goal is to assess whether there is evidence of racial discrimination in the study. In other words, are the variables <code>race</code> and <code>received_callback</code> associated?</p>
<p><strong>Prepare</strong>. Let’s start by writing the null and alternative hypotheses.</p>
<p><span class="math inline">\(H_0:\)</span> There is no association between <code>race</code> and <code>received_callback</code>.</p>
<p><span class="math inline">\(H_a:\)</span> There is an association between <code>race</code> and <code>received_callback</code>.</p>
<p>Next, we can construct a summary graphic. One graphic to explore two categorical variables is a stacked bar plot.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   0.3.5 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.4.1 
✔ readr   2.1.2      ✔ forcats 0.5.1 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>resume_sum <span class="ot">&lt;-</span> resume <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">received_callback =</span> received_callback) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">group_by</span>(race, received_callback) <span class="sc">|&gt;</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'race'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resume_sum, <span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> count)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">fill =</span> received_callback)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="15-connections_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What do you notice about the <code>recieved_callback</code> variable scale? How could we fix that?</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>resume <span class="ot">&lt;-</span> resume <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">received_callback =</span> <span class="fu">as.factor</span>(received_callback))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>resume_sum <span class="ot">&lt;-</span> resume <span class="sc">|&gt;</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>           <span class="fu">group_by</span>(race, received_callback) <span class="sc">|&gt;</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'race'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resume_sum, <span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> count)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">fill =</span> received_callback)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="15-connections_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We might also want to generate a two-way table:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>resume <span class="sc">|&gt;</span> <span class="fu">group_by</span>(race, received_callback) <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> race,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'race'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  received_callback black white
  &lt;fct&gt;             &lt;int&gt; &lt;int&gt;
1 0                  2278  2200
2 1                   157   235</code></pre>
</div>
</div>
<p><strong>Check</strong>: The two assumptions for the test are independence of observations and that all expected counts are larger than 5. We don’t have time to discuss these in detail but we will assume that they are satisfied here.</p>
<p><strong>Calculate</strong>: We next want to calculate a p-value for the hypothesis test. The core <code>tidyverse</code> packages do not offer functionality for hypothesis testing. Instead, there are some functions in base <code>R</code> that perform the various tests. You may have used the <code>lm()</code> function in STAT 213 to perform hypothesis testing in the regression context. <code>t.test()</code> and <code>chisq.test()</code> are a couple of other functions that can perform a one and two-sample t-test (<code>t.test()</code>) or a chi-square goodness-of-fit test and chi-square test of association <code>chisq.test()</code>. The arguments to <code>chisq.test()</code> for a test of association are two vectors. Because the arguments are not <code>data.frame</code>s, we need to specify the appropriate vectors directly with <code>resume$race</code> and <code>resume$received_callback</code>.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="at">x =</span> resume<span class="sc">$</span>race, <span class="at">y =</span> resume<span class="sc">$</span>received_callback)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  resume$race and resume$received_callback
X-squared = 16.449, df = 1, p-value = 4.998e-05</code></pre>
</div>
</div>
<p>The output of <code>chisq.test()</code> gives a p-value of 0.00004998 with a chi-square statistic of 16.449 and 1 degree of freedom.</p>
<p><strong>Conclude</strong>. Finally, we write a conclusion in context of the problem.</p>
<p>There is strong evidence that <code>race</code> and <code>callback</code> are associated. The graph shows that <code>white</code> applicants receive a callback more often than <code>black</code> applicants do and the hypothesis test shows that this is statistically significant.</p>
</section>
<section id="additional-analysis" class="level3" data-number="15.1.2">
<h3 data-number="15.1.2" class="anchored" data-anchor-id="additional-analysis"><span class="header-section-number">15.1.2</span> Additional Analysis</h3>
<p>In addition to carrying out the steps of a statistical hypothesis test, we can also use the skills we have learned in this course to provide further information about the study. Some questions we might answer include:</p>
<ul>
<li><p>what is the distribution of job types <code>job_type</code> and job industries <code>job_industry</code> in the study?</p></li>
<li><p>do some of the first names (<code>firstname</code>) used have more bias than other first names?</p></li>
<li><p>what other variables are associated with whether or not the applicant received a callback?</p></li>
</ul>
<p>To answer the question about the distribution of job types and job industries used in the study, we can make a simple bar plot:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resume, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(<span class="fu">fct_infreq</span>(job_type)))) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Job Type"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="15-connections_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the code, <code>fct_infreq()</code> orders the levels of <code>job_type</code> from the highest count/frequency to the lowest. <code>fct_rev()</code> reverses the order so that, on the resulting bar plot, the level with the highest count appears first.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resume, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(<span class="fu">fct_infreq</span>(job_industry)))) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Job Industry"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="15-connections_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>To answer the question about whether some first names are more biased than others, we might make a graph of the proportion of resumes that received a callback for each first name.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>resume_firstname <span class="ot">&lt;-</span> resume <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(firstname) <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">propcallback =</span> <span class="fu">mean</span>(received_callback <span class="sc">==</span> <span class="st">"1"</span>),</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">gender =</span> <span class="fu">unique</span>(gender),</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">race =</span> <span class="fu">unique</span>(race)) <span class="sc">|&gt;</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(propcallback)) <span class="sc">|&gt;</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unite</span>(<span class="st">"gender_race"</span>, <span class="fu">c</span>(gender, race))</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resume_firstname, <span class="fu">aes</span>(<span class="at">x =</span> gender_race, <span class="at">y =</span> propcallback)) <span class="sc">+</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="15-connections_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can the label the name with the lowest callback rate and the name with the highest callback rate.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>label_df <span class="ot">&lt;-</span> resume_firstname <span class="sc">|&gt;</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(propcallback <span class="sc">==</span> <span class="fu">max</span>(propcallback) <span class="sc">|</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>           propcallback <span class="sc">==</span> <span class="fu">min</span>(propcallback))</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resume_firstname, <span class="fu">aes</span>(<span class="at">x =</span> gender_race, <span class="at">y =</span> propcallback)) <span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_label_repel</span>(<span class="at">data =</span> label_df, <span class="fu">aes</span>(<span class="at">label =</span> firstname))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="15-connections_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="exercise-15-1" class="level3" data-number="15.1.3">
<h3 data-number="15.1.3" class="anchored" data-anchor-id="exercise-15-1"><span class="header-section-number">15.1.3</span> Exercises</h3>
<p>Exercises marked with an * indicate that the exercise has a solution at the end of the chapter at @ref(solutions-15).</p>
<ol type="1">
<li><p>Construct a graphic or make a table that explores whether one of the other variables in the data set is associated with whether the applicant receives a callback for the job. Other variables include <code>gender</code>, <code>years_college</code>, <code>college_degree</code>, <code>honors</code>, <code>worked_during_school</code>, <code>years_experience</code>, <code>computer_skills</code>, <code>special_skills</code>, <code>volunteer</code>, <code>military</code>, <code>employment_holes</code>, and <code>resume_quality</code>.</p></li>
<li><p>Construct a graphic or make a table that explores one of the other variables in the data set is associated with whether the applicant receives a callback for the job. If your variable in Exercise 1 was categorical, choose a quantitative variable for this exercise. If your variable in Exercise 1 was quantitative, choose a categorical variable for this exercise.</p></li>
<li><p>For the categorical variable that you chose, conduct a Chi-square test of association to see if there is statistical evidence that the variable is associated with <code>received_callback</code>. In your test, (a), write the null and alternative hypotheses, run the test in <code>chisq.test()</code> and make a note of whether or not you get a warning about assumptions for the test, and write a conclusion in context of the problem.</p></li>
<li><p>Write a short, one paragraph summary on your major take-aways from this section.</p></li>
</ol>
</section>
</section>
<section id="stat-213" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="stat-213"><span class="header-section-number">15.2</span> STAT 213</h2>
<p>Much of the same concepts in connecting STAT 113 to this course hold for connecting STAT 213 with this course. We can still use what we have learned to explore a data set, conduct a hypothesis test, and perform further analysis and exploration on the data set.</p>
<p>For this section, however, we will focus more on a tidy approach to modeling. In particular, we will use the <code>broom</code> package to return <code>tibble</code>s with model summary information that we can then use for further analysis, plotting, or presentation.</p>
<p>We will use the <code>coffee_ratings</code> data set, which contains observations on ratings of various coffees throughout the world. The data was obtained from the Github account (<a href="https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-07-07/readme.md" class="uri">https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-07-07/readme.md</a>).</p>
<p>A description of each variable in the data set is given below.</p>
<ul>
<li><code>total_cup_points</code>, the score of the coffee by a panel of experts (our response variable for this section)</li>
<li><code>species</code>, the species of the coffee bean (Arabica or Robusta)</li>
<li><code>aroma</code>, aroma (smell) grade</li>
<li><code>flavor</code>, flavor grade</li>
<li><code>aftertaste</code>, aftertaste grade</li>
<li><code>acidity</code>, acidity grade</li>
<li><code>body</code>, body grade</li>
<li><code>balance</code>, balance grade</li>
<li><code>uniformity</code>, uniformity grade</li>
<li><code>clean_cup</code>, clean cup grade</li>
<li><code>sweetness</code>, sweetness grade</li>
<li><code>moisture</code>, moisture grade</li>
<li><code>category_one_defects</code>, count of category one defects</li>
<li><code>quakers</code>, quakers</li>
<li><code>category_two_defects</code>, the number of category two defects</li>
</ul>
<section id="broom-package-functions" class="level3" data-number="15.2.1">
<h3 data-number="15.2.1" class="anchored" data-anchor-id="broom-package-functions"><span class="header-section-number">15.2.1</span> <code>broom</code> Package Functions</h3>
<p>The <code>broom</code> package consists of three primary functions: <code>tidy()</code>, <code>glance()</code>, and <code>augment()</code>.</p>
<p><strong><code>tidy()</code></strong></p>
<p><code>tidy()</code> is analagous to <code>summary()</code> for a linear model object. Let’s start by fitting a linear model with <code>lm()</code> with <code>total_cup_points</code> as the response and <code>species</code>, <code>aroma</code>, <code>flavor</code>, <code>sweetness</code>, and <code>moisture</code> as predictors.</p>
<p>Read in the data, load the <code>broom</code> package (and install it with <code>install.packages("broom")</code>), and fit the model with</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at /Users/highamm/Desktop/ds234_quarto</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>coffee_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data/coffee_ratings.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1339 Columns: 43</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (24): species, owner, country_of_origin, farm_name, lot_number, mill, ic...
dbl (19): total_cup_points, number_of_bags, aroma, flavor, aftertaste, acidi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>coffee_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(total_cup_points <span class="sc">~</span> species <span class="sc">+</span> aroma <span class="sc">+</span> flavor <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                   sweetness <span class="sc">+</span> moisture,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> coffee_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In STAT 213, you likely used <code>summary()</code> to look at the model output:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(coffee_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = total_cup_points ~ species + aroma + flavor + sweetness + 
    moisture, data = coffee_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.5132 -0.3705  0.0726  0.5610  5.5844 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     7.04039    0.77377   9.099  &lt; 2e-16 ***
speciesRobusta  2.85365    0.26861  10.624  &lt; 2e-16 ***
aroma           1.95188    0.14575  13.392  &lt; 2e-16 ***
flavor          5.09440    0.14042  36.281  &lt; 2e-16 ***
sweetness       2.23956    0.06553  34.173  &lt; 2e-16 ***
moisture       -1.88033    0.67368  -2.791  0.00533 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.168 on 1333 degrees of freedom
Multiple R-squared:  0.8891,    Adjusted R-squared:  0.8887 
F-statistic:  2137 on 5 and 1333 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>However, there are a few inconveniences involving <code>summary()</code>. First, it’s just not that nice to look at: the output isn’t formatted in a way that is easy to look at. Second, it can be challenging to pull items from the summary output with code. For example, if you want to pull the p-value for <code>moisture</code>, you would need to write something like:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(coffee_mod)<span class="sc">$</span>coefficients[<span class="st">"moisture"</span>, <span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.005327594</code></pre>
</div>
</div>
<p><code>tidy()</code> is an alternative that puts the model coefficients, standard errors, t-stats, and p-values in a tidy tibble:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(coffee_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  term           estimate std.error statistic   p.value
  &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)        7.04    0.774       9.10 3.23e- 19
2 speciesRobusta     2.85    0.269      10.6  2.31e- 25
3 aroma              1.95    0.146      13.4  1.82e- 38
4 flavor             5.09    0.140      36.3  4.73e-201
5 sweetness          2.24    0.0655     34.2  2.41e-184
6 moisture          -1.88    0.674      -2.79 5.33e-  3</code></pre>
</div>
</div>
<p>The advantage of this format of output is that we can now use other <code>tidyverse</code> functions on the output. To pull the p-values,</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(coffee_mod) <span class="sc">|&gt;</span> <span class="fu">select</span>(p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1
    p.value
      &lt;dbl&gt;
1 3.23e- 19
2 2.31e- 25
3 1.82e- 38
4 4.73e-201
5 2.41e-184
6 5.33e-  3</code></pre>
</div>
</div>
<p>or, to grab the output for a particular variable of interest:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(coffee_mod) <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"aroma"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  term  estimate std.error statistic  p.value
  &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 aroma     1.95     0.146      13.4 1.82e-38</code></pre>
</div>
</div>
<p><strong><code>glance()</code></strong></p>
<p><code>glance()</code> puts some model summary statistics into a tidy tibble. For example, if we run</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(coffee_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squ…¹ adj.r…² sigma stati…³ p.value    df logLik   AIC   BIC devia…⁴ df.re…⁵
    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;int&gt;
1   0.889   0.889  1.17   2137.       0     5 -2105. 4224. 4260.   1818.    1333
# … with 1 more variable: nobs &lt;int&gt;, and abbreviated variable names
#   ¹​r.squared, ²​adj.r.squared, ³​statistic, ⁴​deviance, ⁵​df.residual</code></pre>
</div>
</div>
<p>you should notice a lot of statistics that you are familiar with from STAT 213, including <code>r.squared</code>, <code>adj.r.squared</code>, <code>sigma</code> (the residual standard error), <code>statistic</code> (the overall F-statistic), <code>AIC</code>, and <code>BIC</code>.</p>
<p><strong><code>augment()</code></strong></p>
<p><code>augment()</code> is my personal favourite of the three. The function returns a <code>tibble</code> that contains all of the variables used to fit the model appended with commonly used diagnostic statistics like the fitted values (<code>.fitted)</code>, cook’s distance (<code>.cooksd)</code>, <code>.hat</code> values for leverage, and residuals (<code>.resid</code>).</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(coffee_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,339 × 12
   total_c…¹ species aroma flavor sweet…² moist…³ .fitted  .resid    .hat .sigma
       &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
 1      90.6 Arabica  8.67   8.83   10       0.12    91.1 -0.537  0.0112    1.17
 2      89.9 Arabica  8.75   8.67   10       0.12    90.5 -0.538  0.0103    1.17
 3      89.8 Arabica  8.42   8.5    10       0       89.2  0.577  0.00745   1.17
 4      89   Arabica  8.17   8.58   10       0.11    88.9  0.114  0.00784   1.17
 5      88.8 Arabica  8.25   8.5    10       0.12    88.6  0.214  0.00669   1.17
 6      88.8 Arabica  8.58   8.42   10       0.11    88.9 -0.0411 0.00726   1.17
 7      88.8 Arabica  8.42   8.5    10       0.11    89.0 -0.216  0.00655   1.17
 8      88.7 Arabica  8.25   8.33    9.33    0.03    86.4  2.25   0.00728   1.17
 9      88.4 Arabica  8.67   8.67    9.33    0.03    89.0 -0.550  0.0122    1.17
10      88.2 Arabica  8.08   8.58   10       0.1     88.7 -0.479  0.00826   1.17
# … with 1,329 more rows, 2 more variables: .cooksd &lt;dbl&gt;, .std.resid &lt;dbl&gt;,
#   and abbreviated variable names ¹​total_cup_points, ²​sweetness, ³​moisture</code></pre>
</div>
</div>
<p><code>augment()</code> the data set makes it really easy to do things like:</p>
<ul>
<li><code>filter()</code> the data set to examine values with high cook’s distance that might be influential</li>
</ul>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>augment_df <span class="ot">&lt;-</span> <span class="fu">augment</span>(coffee_mod)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>augment_df <span class="sc">|&gt;</span> <span class="fu">filter</span>(.cooksd <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  total_cup_p…¹ species aroma flavor sweet…² moist…³ .fitted .resid  .hat .sigma
          &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1             0 Arabica     0      0       0    0.12    6.81  -6.81 0.430   1.14
# … with 2 more variables: .cooksd &lt;dbl&gt;, .std.resid &lt;dbl&gt;, and abbreviated
#   variable names ¹​total_cup_points, ²​sweetness, ³​moisture</code></pre>
</div>
</div>
<p>We see right away that there is a potentially influential observation with <code>0</code> <code>total_cup_points</code>. Examining this variable further, we see that it is probably a data entry error that can be removed from the data.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> coffee_df, <span class="fu">aes</span>(<span class="at">x =</span> total_cup_points)) <span class="sc">+</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">15</span>, <span class="at">fill =</span> <span class="st">"white"</span>, <span class="at">colour =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="15-connections_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We could also find observations with high leverage</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>augment_df <span class="sc">|&gt;</span> <span class="fu">filter</span>(.hat <span class="sc">&gt;</span> <span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 12
  total_cup_p…¹ species aroma flavor sweet…² moist…³ .fitted .resid  .hat .sigma
          &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1          59.8 Arabica   7.5   6.67    1.33    0.1    58.4    1.38 0.223   1.17
2           0   Arabica   0     0       0       0.12    6.81  -6.81 0.430   1.14
# … with 2 more variables: .cooksd &lt;dbl&gt;, .std.resid &lt;dbl&gt;, and abbreviated
#   variable names ¹​total_cup_points, ²​sweetness, ³​moisture</code></pre>
</div>
</div>
<p>or observations that are outliers:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>augment_df <span class="sc">|&gt;</span> <span class="fu">filter</span>(.std.resid <span class="sc">&gt;</span> <span class="dv">3</span> <span class="sc">|</span> .std.resid <span class="sc">&lt;</span> <span class="sc">-</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 12
   total_cu…¹ species aroma flavor sweet…² moist…³ .fitted .resid    .hat .sigma
        &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
 1       82.8 Arabica  8.08   8.17   10       0.12    86.6  -3.85 0.00359   1.16
 2       82.4 Arabica  5.08   7.75   10       0.11    78.6   3.79 0.111     1.16
 3       82.3 Arabica  7.75   8.08    6.67    0.11    78.1   4.27 0.0421    1.16
 4       80.7 Arabica  7.67   7.5     6.67    0       75.2   5.51 0.0347    1.16
 5       80   Arabica  7.58   7.75   10       0       83.7  -3.71 0.00388   1.16
 6       79.9 Arabica  7.83   7.67   10       0       83.8  -3.87 0.00365   1.16
 7       79.2 Arabica  7.17   7.42    6.67    0.1     73.6   5.58 0.0337    1.16
 8       78.6 Arabica  7.92   7.58   10       0.1     83.3  -4.74 0.00232   1.16
 9       78.3 Arabica  7.17   6.08   10       0.11    74.2   4.13 0.0199    1.16
10       77.6 Arabica  7.58   7.67    6       0.12    74.1   3.46 0.0518    1.16
# … with 15 more rows, 2 more variables: .cooksd &lt;dbl&gt;, .std.resid &lt;dbl&gt;, and
#   abbreviated variable names ¹​total_cup_points, ²​sweetness, ³​moisture</code></pre>
</div>
</div>
<p>Finally, we can use our <code>ggplot2</code> skills to construct plots like a residuals versus fitted values plot (filtering out the outlying observation first):</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> augment_df <span class="sc">|&gt;</span> <span class="fu">filter</span>(.fitted <span class="sc">&gt;</span> <span class="dv">25</span>), <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="15-connections_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="exploring-concepts" class="level3" data-number="15.2.2">
<h3 data-number="15.2.2" class="anchored" data-anchor-id="exploring-concepts"><span class="header-section-number">15.2.2</span> Exploring Concepts</h3>
<p>We can also use our data science skills to explore concepts that you may or may not have found difficult in STAT 213. In this section, we will use plotting to help interpret coefficient estimates in models with two quantitative predictors: one with an interaction and one without an interaction.</p>
<p>First, consider a model with <code>flavor</code> and <code>moisture</code> as predictors on the coffee data set that removes the observation with a <code>total_cup_points</code> rating of <code>0</code>:</p>
<p><span class="math inline">\(Y = \beta_0 + \beta_1 flavor + \beta_2 aroma + \epsilon\)</span></p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>coffee_noout <span class="ot">&lt;-</span> coffee_df <span class="sc">|&gt;</span> <span class="fu">filter</span>(total_cup_points <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>coffee_fa <span class="ot">&lt;-</span> <span class="fu">lm</span>(total_cup_points <span class="sc">~</span> flavor <span class="sc">+</span> aroma,</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> coffee_noout)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>coffee_fa <span class="sc">|&gt;</span> <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    29.8      1.01      29.6  1.79e-148
2 flavor          5.55     0.177     31.4  1.33e-162
3 aroma           1.39     0.191      7.27 6.11e- 13</code></pre>
</div>
</div>
<p>You might recall that, you can interpret the estimate for <span class="math inline">\(\hat{\beta}_1\)</span> as something like:</p>
<p>“For a one point increase in flavor grade, we expect average coffee score to increase by 5.55 points, if <code>aroma</code> is held constant.”</p>
<p>(or, if <code>aroma</code> does not change, or if <code>aroma</code> is fixed).</p>
<p>But, what if someone asked you, what does that mean, “if <code>aroma</code> is held constant.” Instead of using words to explain, we can use our <code>ggplot2</code> skills to construct a plot. The plot that we are going to create is going to show the fitted model for <strong>5</strong> distinct values of <code>aroma</code>: the minimum value, Q1, the median, Q3, and the maximum (though these values can also be chosen arbitrarily). We will make use of the <code>modelr</code> package to gather predictions to make the lines in our plot. First, we are creating a grid of values for predictions:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="do">## install.packages("modelr")</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'modelr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:broom':

    bootstrap</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>grid_vals <span class="ot">&lt;-</span> coffee_noout <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  modelr<span class="sc">::</span><span class="fu">data_grid</span>(</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">flavor =</span> <span class="fu">quantile</span>(flavor),</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">aroma =</span> <span class="fu">quantile</span>(aroma)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>grid_vals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 2
   flavor aroma
    &lt;dbl&gt; &lt;dbl&gt;
 1   6.08  5.08
 2   6.08  7.42
 3   6.08  7.58
 4   6.08  7.75
 5   6.08  8.75
 6   7.33  5.08
 7   7.33  7.42
 8   7.33  7.58
 9   7.33  7.75
10   7.33  8.75
# … with 15 more rows</code></pre>
</div>
</div>
<p>We then gather these predictions in a data set, and use that data set to make the lines in our plot. The plot will show <code>total_cup_points</code> on the y-axis, <code>flavor</code> on the x-axis, and have coloured lines for a few different values of <code>aroma</code> that we specified in the grid function:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> grid_vals <span class="sc">|&gt;</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  modelr<span class="sc">::</span><span class="fu">gather_predictions</span>(coffee_fa)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>grid</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 4
   model     flavor aroma  pred
   &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 coffee_fa   6.08  5.08  70.7
 2 coffee_fa   6.08  7.42  73.9
 3 coffee_fa   6.08  7.58  74.1
 4 coffee_fa   6.08  7.75  74.4
 5 coffee_fa   6.08  8.75  75.8
 6 coffee_fa   7.33  5.08  77.6
 7 coffee_fa   7.33  7.42  80.9
 8 coffee_fa   7.33  7.58  81.1
 9 coffee_fa   7.33  7.75  81.3
10 coffee_fa   7.33  8.75  82.7
# … with 15 more rows</code></pre>
</div>
</div>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> coffee_noout, <span class="fu">aes</span>(<span class="at">x =</span> flavor, <span class="at">y =</span> total_cup_points)) <span class="sc">+</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> grid, <span class="fu">aes</span>(<span class="at">colour =</span> <span class="fu">fct_rev</span>(<span class="fu">factor</span>(aroma)),</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">y =</span> pred), <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">"Aroma"</span>) <span class="sc">+</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="15-connections_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From this model, we might more easily be able to explain that slope interpretation earlier: <strong>for a fixed coloured line of <code>aroma</code></strong>, if flavor increases by one point, we expect coffee rating to increase by 5.55 points, on average.</p>
<p>But, we can really see the power of <code>modelr</code> and plotting models if we fit more complicated models. For example, next, we will fit a model with an interaction between <code>flavor</code> and <code>aroma</code>. You may recall that an interaction allows the association between one predictor (<code>flavor</code>) and the response (<code>total_cup_points</code>) to change depending on the value of the other predictor (<code>aroma</code>).</p>
<p><span class="math inline">\(Y = \beta_0 + \beta_1 flavor + \beta_2 aroma + \beta_3 flavor * aroma + \epsilon\)</span></p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>coffee_fa_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(total_cup_points <span class="sc">~</span> flavor <span class="sc">+</span> aroma <span class="sc">+</span> flavor<span class="sc">:</span>aroma,</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> coffee_noout)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>coffee_fa_int <span class="sc">|&gt;</span> <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term         estimate std.error statistic  p.value
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)    -38.5     13.4       -2.88 4.02e- 3
2 flavor          14.6      1.77       8.24 4.06e-16
3 aroma           10.5      1.79       5.88 5.26e- 9
4 flavor:aroma    -1.21     0.235     -5.13 3.34e- 7</code></pre>
</div>
</div>
<p>You may also recall that, in a model with an interaction between two quantitative variables, the coefficient estimates are not interpretable on their own. We <strong>cannot</strong> say something like “For a one point increase in flavor, we expect average coffee rating to increase by 14.6 points, as long as <code>aroma</code> and the interaction between <code>flavor</code> and <code>aroma</code> is held constant” because it does not make sense to talk about an increase in one unit of <code>flavor</code> while also holding the interaction fixed.</p>
<p>So, for interpreting the model output, we can again use the <code>modelr</code> package and out <code>ggplot2</code> knowledge to construct a plot that shows the relationship between <code>total_cup_points</code> and <code>flavor</code> for a few different values of <code>aroma</code>:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> coffee_noout <span class="sc">|&gt;</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  modelr<span class="sc">::</span><span class="fu">data_grid</span>(</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">flavor =</span> <span class="fu">quantile</span>(flavor),</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">aroma =</span> <span class="fu">quantile</span>(aroma), </span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>  modelr<span class="sc">::</span><span class="fu">gather_predictions</span>(coffee_fa_int)</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> coffee_noout, <span class="fu">aes</span>(<span class="at">x =</span> flavor, <span class="at">y =</span> total_cup_points)) <span class="sc">+</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> grid, <span class="fu">aes</span>(<span class="at">colour =</span> <span class="fu">fct_rev</span>(<span class="fu">factor</span>(aroma)), <span class="at">y =</span> pred), <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">"Aroma"</span>) <span class="sc">+</span></span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="15-connections_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># grid &lt;- coffee_noout |&gt;</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   modelr::data_grid(</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="co">#     flavor = quantile(aroma),</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="co">#     aroma = quantile(flavor), </span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="co">#   ) |&gt;</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a><span class="co">#   modelr::gather_predictions(coffee_fa_int)</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a><span class="co"># coffee_noout &lt;- coffee_noout |&gt; mutate(flavor_cut = cut(flavor, breaks = 5))</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a><span class="co"># ggplot(data = coffee_noout, aes(x = aroma, y = total_cup_points)) +</span></span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a><span class="co">#   geom_point(alpha = 0.2, aes(colour = flavor_cut)) +</span></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a><span class="co">#   geom_smooth(aes(colour = flavor_cut), method = "lm", fullrange = TRUE, se = FALSE) +</span></span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a><span class="co">#   scale_colour_viridis_d() +</span></span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a><span class="co">#   theme_minimal()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From the plot, we can understand the nature of the interaction a little better. It looks like, no matter what the value of <code>aroma</code>, <code>flavor</code> and <code>total_cup_points</code> have a positive association. But, for larger values of <code>aroma</code>, the slope is smaller while, for smaller values of <code>aroma</code>, the slope is larger. The model says that, when <code>aroma</code> is small, we would expect a larger increase in <code>total_cup_points</code> (on average) for a one point increase in <code>flavor</code> while, when <code>aroma</code> is large, we would expect a smaller increase in <code>total_cup_points</code> (on average) for a one point increase in <code>flavor</code>.</p>
</section>
<section id="exercise-15-2" class="level3" data-number="15.2.3">
<h3 data-number="15.2.3" class="anchored" data-anchor-id="exercise-15-2"><span class="header-section-number">15.2.3</span> Exercises</h3>
<p>Exercises marked with an * indicate that the exercise has a solution at the end of the chapter at @ref(solutions-15).</p>
<ol type="1">
<li><p>Add a couple of more predictors to the linear model that we fit earlier. Then, use <code>glance()</code> to obtain some model fit statistics. Which model is “better” according to some of the metrics you learned about in STAT 213?</p></li>
<li><p>For one of your fitted models, construct a histogram of the residuals to assess the normality assumption (using <code>ggplot2</code> and <code>augment()</code>).</p></li>
<li><p>Make a table of the 5 coffees that have the highest <strong>predicted</strong> coffee rating, according to one of your models.</p></li>
<li><p>Re-examine the interaction model plot that had <code>total_cup_points</code> on the y-axis, <code>flavor</code> on the x-axis, and coloured lines for <code>aroma</code>. Change the plotso that, <code>aroma</code> is on the x-axis and the five coloured lines correspond to the quantiles of <code>flavor</code>. This allows us to explore how the association between <code>total_cup_points</code> and <code>aroma</code> changes for different values of <code>flavor</code>.</p></li>
<li><p>Write a short, one paragraph summary on your major take-aways from this section.</p></li>
</ol>
</section>
</section>
<section id="cs-140" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="cs-140"><span class="header-section-number">15.3</span> CS 140</h2>
<p>In this section, we will repeat a couple of topics from CS 140, which is in Python, in <code>R</code>. In particular we will,</p>
<ul>
<li><p>write our own function. The syntax for doing so in <code>R</code> is <strong>very</strong> similar to Python.</p></li>
<li><p>perform iteration to repeat a similar task multiple times.</p></li>
</ul>
<p>To start, suppose that we are interested in scraping some hitting data on SLU’s baseball team from the web address <a href="https://saintsathletics.com/sports/baseball/stats/2022" class="uri">https://saintsathletics.com/sports/baseball/stats/2022</a>. After we have the hitting data, we want to create a statistic for each player’s weighted on-base-average (<code>wOBA</code>). Information on what the <code>wOBA</code> is can be found here: <a href="https://www.mlb.com/glossary/advanced-stats/weighted-on-base-average" class="uri">https://www.mlb.com/glossary/advanced-stats/weighted-on-base-average</a>. Some of the following code was modified from a project completed by Jack Sylvia in a data visualization course.</p>
<p>Code to do such a task is given in the following chunk.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rvest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'rvest'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:readr':

    guess_encoding</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>url_SLU <span class="ot">&lt;-</span> <span class="st">"https://saintsathletics.com/sports/baseball/stats/2022"</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>tab_SLU <span class="ot">&lt;-</span> <span class="fu">read_html</span>(url_SLU) <span class="sc">|&gt;</span> <span class="fu">html_nodes</span>(<span class="st">"table"</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>SLU_Hitting <span class="ot">&lt;-</span> tab_SLU[[<span class="dv">1</span>]] <span class="sc">|&gt;</span> <span class="fu">html_table</span>(<span class="at">fill =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="sc">-</span><span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="dv">23</span>) <span class="sc">|&gt;</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">wOBA =</span> (<span class="fl">0.69</span> <span class="sc">*</span> BB <span class="sc">+</span> <span class="fl">0.72</span> <span class="sc">*</span> HBP <span class="sc">+</span> <span class="fl">0.89</span> <span class="sc">*</span> (H<span class="sc">-</span><span class="st">`</span><span class="at">2B</span><span class="st">`</span><span class="sc">-</span><span class="st">`</span><span class="at">3B</span><span class="st">`</span><span class="sc">-</span><span class="st">`</span><span class="at">HR</span><span class="st">`</span>) <span class="sc">+</span> <span class="fl">1.27</span> <span class="sc">*</span> <span class="st">`</span><span class="at">2B</span><span class="st">`</span> <span class="sc">+</span> <span class="fl">1.62</span> <span class="sc">*</span> <span class="st">`</span><span class="at">3B</span><span class="st">`</span> <span class="sc">+</span> <span class="fl">2.10</span> <span class="sc">*</span> HR) <span class="sc">/</span> (AB <span class="sc">+</span> BB <span class="sc">+</span> SF <span class="sc">+</span> HBP))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can make sure that the statistic was calculated with:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>SLU_Hitting <span class="sc">|&gt;</span> <span class="fu">select</span>(wOBA, <span class="fu">everything</span>()) <span class="sc">|&gt;</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(wOBA))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 23
    wOBA   `#` Player      AVG   OPS `GP-GS`    AB     R     H  `2B`  `3B`    HR
   &lt;dbl&gt; &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
 1 0.514     7 "Brinker… 0.556 1.16  5-1         9     3     5     0     0     0
 2 0.497    25 "Liberat… 0.379 1.16  25-19      66    19    25     8     0     4
 3 0.46      1 "Verrast… 0.5   1.1   4-0         2     1     1     0     0     0
 4 0.452    13 "Butler,… 0.325 1.08  35-35     126    31    41     9     5     7
 5 0.433     6 "Clark, … 0.367 1.02  29-19      79    24    29     5     2     3
 6 0.425    11 "Circell… 0.252 1.00  35-33     111    27    28     9     0    11
 7 0.412     9 "Burke, … 0.308 0.885 6-4        13     4     4     1     0     0
 8 0.391    30 "Watson,… 0.318 0.853 35-33     110    29    35     6     0     1
 9 0.365    19 "Delaney… 0.33  0.817 34-34     115    18    38     5     1     1
10 0.358     8 "Forgion… 0.244 0.799 27-27      86    22    21     4     0     4
11 0.356     5 "Desjard… 0.284 0.741 28-20      67    23    19     1     0     0
12 0.347    37 "Goretti… 0.268 0.771 32-32      97    18    26     6     3     0
13 0.345     3 "Haun, H… 0     0.5   11-0        2     1     0     0     0     0
14 0.335    18 "Federic… 0.275 0.733 25-7       40    13    11     3     0     0
15 0.309    23 "Connor,… 0.286 0.661 6-0         7     2     2     0     0     0
16 0.294    22 "Courtwr… 0.256 0.63  20-10      39     7    10     1     0     0
17 0.292    20 "Courtwr… 0.281 0.646 27-17      64     6    18     2     0     0
18 0.285    41 "Comerfo… 0.222 0.582 31-21      72    16    16     0     0     0
19 0.154    24 "Colange… 0.095 0.295 15-3       21     6     2     0     0     0
20 0        36 "Bolduc,… 0     0     2-0         2     0     0     0     0     0
# … with 11 more variables: RBI &lt;int&gt;, TB &lt;int&gt;, `SLG%` &lt;dbl&gt;, BB &lt;int&gt;,
#   HBP &lt;int&gt;, SO &lt;int&gt;, GDP &lt;int&gt;, `OB%` &lt;dbl&gt;, SF &lt;int&gt;, SH &lt;int&gt;,
#   `SB-ATT` &lt;chr&gt;</code></pre>
</div>
</div>
<section id="functions" class="level3" data-number="15.3.1">
<h3 data-number="15.3.1" class="anchored" data-anchor-id="functions"><span class="header-section-number">15.3.1</span> Functions</h3>
<p>Now, suppose that we might want to repeat the scraping and calculation of <code>wOBA</code> for other years at SLU or for other teams. We could, of course, obtain the new URL address and copy and paste the code that we used above, replacing the old URL address with the new one. This would be a reasonable thing to do if we only wanted to do this for <em>one</em> other url. But, if we wanted to do this for 10, 20, 50, 1000, urls, we might consider writing a function to scrape the data and calculate the <code>wOBA</code>.</p>
<p>The format of a function in <code>R</code> is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>name_of_function <span class="ot">&lt;-</span> <span class="cf">function</span>(argument1, argument2, ....) {</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  body_of_function <span class="do">## performs various tasks with the arguments</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(output) <span class="do">## tells the function what to return</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have used functions throughout the entire semester, but they have always been functions that others have defined and are imported into <code>R</code> through packages. As we expand our toolbox, we might encounter situations where we want to write our own specialized functions for performing tasks that are not covered by functions that others have written.</p>
<p>Before we get back to our example, let’s write a very simple function, called <code>get_sum_squares</code>, that computes the sum of squares from a numeric vector argument named <code>x_vec</code>. A sum of squares function would take each number in <code>x_vec</code>, square it, and then add the numbers up.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>get_sum_squares <span class="ot">&lt;-</span> <span class="cf">function</span>(x_vec) {</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  sum_of_squares <span class="ot">&lt;-</span> <span class="fu">sum</span>(x_vec <span class="sc">^</span> <span class="dv">2</span>)</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(sum_of_squares)</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, let’s test our function on the numeric vector <code>c(2, 4, 1)</code></p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_sum_squares</span>(<span class="at">x_vec =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21</code></pre>
</div>
</div>
<p>Now, we will move back to our example. We want to write a function called <code>get_hitting_data</code> that takes a <code>url_name</code>, scrapes the data from that url, and calculates the <code>wOBA</code> from the variables that were scraped. Note that our function will only work on urls that contain a data table formatted with the various baseball statistics as column names.</p>
<p>To create this function, we can simply copy and paste the code above and replace the SLU url web address with the argument <code>url_name</code> in the body of the function.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>get_hitting_data <span class="ot">&lt;-</span> <span class="cf">function</span>(url_name) {</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  tab <span class="ot">&lt;-</span> <span class="fu">read_html</span>(url_name) <span class="sc">|&gt;</span> <span class="fu">html_nodes</span>(<span class="st">"table"</span>)</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>  hitting <span class="ot">&lt;-</span> tab[[<span class="dv">1</span>]] <span class="sc">|&gt;</span> <span class="fu">html_table</span>(<span class="at">fill =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="sc">-</span><span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span><span class="dv">23</span>) <span class="sc">|&gt;</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">wOBA =</span> (<span class="fl">0.69</span> <span class="sc">*</span> BB <span class="sc">+</span> <span class="fl">0.72</span> <span class="sc">*</span> HBP <span class="sc">+</span> <span class="fl">0.89</span> <span class="sc">*</span></span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>                     (H<span class="sc">-</span> <span class="st">`</span><span class="at">2B</span><span class="st">`</span> <span class="sc">-</span> <span class="st">`</span><span class="at">3B</span><span class="st">`</span> <span class="sc">-</span> <span class="st">`</span><span class="at">HR</span><span class="st">`</span>) <span class="sc">+</span></span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a>                     <span class="fl">1.27</span> <span class="sc">*</span> <span class="st">`</span><span class="at">2B</span><span class="st">`</span> <span class="sc">+</span> <span class="fl">1.62</span> <span class="sc">*</span> <span class="st">`</span><span class="at">3B</span><span class="st">`</span> <span class="sc">+</span> <span class="fl">2.10</span> <span class="sc">*</span> HR) <span class="sc">/</span> </span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a>             (AB <span class="sc">+</span> BB <span class="sc">+</span> SF <span class="sc">+</span> HBP),</span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">url_name =</span> url_name)</span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(hitting)</span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can then test our function on the SLU url:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_hitting_data</span>(<span class="at">url_name =</span> <span class="st">"https://saintsathletics.com/sports/baseball/stats/2022"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 24
     `#` Player      AVG   OPS `GP-GS`    AB     R     H  `2B`  `3B`    HR   RBI
   &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
 1     6 "Clark, … 0.367 1.02  29-19      79    24    29     5     2     3    23
 2    19 "Delaney… 0.33  0.817 34-34     115    18    38     5     1     1    24
 3    13 "Butler,… 0.325 1.08  35-35     126    31    41     9     5     7    36
 4    30 "Watson,… 0.318 0.853 35-33     110    29    35     6     0     1    20
 5     5 "Desjard… 0.284 0.741 28-20      67    23    19     1     0     0     9
 6    20 "Courtwr… 0.281 0.646 27-17      64     6    18     2     0     0    13
 7    37 "Goretti… 0.268 0.771 32-32      97    18    26     6     3     0    14
 8    11 "Circell… 0.252 1.00  35-33     111    27    28     9     0    11    35
 9     8 "Forgion… 0.244 0.799 27-27      86    22    21     4     0     4    17
10    41 "Comerfo… 0.222 0.582 31-21      72    16    16     0     0     0     6
11     7 "Brinker… 0.556 1.16  5-1         9     3     5     0     0     0     2
12     1 "Verrast… 0.5   1.1   4-0         2     1     1     0     0     0     1
13    25 "Liberat… 0.379 1.16  25-19      66    19    25     8     0     4    20
14     9 "Burke, … 0.308 0.885 6-4        13     4     4     1     0     0     2
15    23 "Connor,… 0.286 0.661 6-0         7     2     2     0     0     0     1
16    18 "Federic… 0.275 0.733 25-7       40    13    11     3     0     0     8
17    22 "Courtwr… 0.256 0.63  20-10      39     7    10     1     0     0     5
18    24 "Colange… 0.095 0.295 15-3       21     6     2     0     0     0     2
19     3 "Haun, H… 0     0.5   11-0        2     1     0     0     0     0     0
20    36 "Bolduc,… 0     0     2-0         2     0     0     0     0     0     0
# … with 12 more variables: TB &lt;int&gt;, `SLG%` &lt;dbl&gt;, BB &lt;int&gt;, HBP &lt;int&gt;,
#   SO &lt;int&gt;, GDP &lt;int&gt;, `OB%` &lt;dbl&gt;, SF &lt;int&gt;, SH &lt;int&gt;, `SB-ATT` &lt;chr&gt;,
#   wOBA &lt;dbl&gt;, url_name &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="iteration" class="level3" data-number="15.3.2">
<h3 data-number="15.3.2" class="anchored" data-anchor-id="iteration"><span class="header-section-number">15.3.2</span> Iteration</h3>
<p>Now suppose that we want to use our function to scrape the 2022 baseball statistics for all teams in the Liberty League. There are 10 teams in total. The websites for each team’s statistics as well as the school name is given in the <code>tibble</code> below:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>school_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">school_name =</span> <span class="fu">c</span>(<span class="st">"SLU"</span>, <span class="st">"Clarkson"</span>, <span class="st">"Rochester"</span>, <span class="st">"RIT"</span>, <span class="st">"Ithaca"</span>, <span class="st">"Skidmore"</span>, <span class="st">"RPI"</span>, <span class="st">"Union"</span>, <span class="st">"Bard"</span>, <span class="st">"Vassar"</span>),</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">hitting_web_url =</span> <span class="fu">c</span>(<span class="st">"https://saintsathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://clarksonathletics.com/sports/baseball/stats/2022"</span>, </span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://uofrathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://ritathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://athletics.ithaca.edu/sports/baseball/stats/2022"</span>,</span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://skidmoreathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://rpiathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://unionathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://bardathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://www.vassarathletics.com/sports/baseball/stats/2022"</span>))</span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a>school_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>One option we have to obtain the hitting statistics for all 10 teams and calculating the <code>wOBA</code> (assuming that the tables are structured the same way on each web page) would be to apply our function 10 times and then bind together the results. The first three applications of the function are shown below.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_hitting_data</span>(<span class="at">url_name =</span> <span class="st">"https://saintsathletics.com/sports/baseball/stats/2022"</span>)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_hitting_data</span>(<span class="at">url_name =</span> <span class="st">"https://clarksonathletics.com/sports/baseball/stats/2022"</span>)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">get_hitting_data</span>(<span class="at">url_name =</span> <span class="st">"https://uofrathletics.com/sports/baseball/stats/2022"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For just 10 teams, this approach is certainly doable but is a bit annoying. And, what if we wanted to do this type of calculation for a league with more teams, such as the MLB (Major League Baseball)? Or, for multiple years for each team?</p>
<p>A better approach is to use <strong>iteration</strong> and write code to repeatedly scrape the data from each website and calculate the <code>wOBA</code> statistic with our function. In CS 140, the primary form of iteration you used was probably a <code>for</code> loop. <code>for</code> loops in <code>R</code> have very similar syntax to <code>for</code> loops in Python. However, in general, <code>for</code> loops are clunky, can take up a lot of lines of code, and can be difficult to read.</p>
<p>For this section, we will instead focus on a <strong>functional programming</strong> approach to iteration through the <code>map()</code> function family in <code>purrr</code>. <code>purrr</code> is part of the core <code>tidyverse</code> so the package gets loaded in with <code>library(tidyverse)</code>. The <code>map()</code> function has two arguments: the first is a vector or a list and the second is a function. <code>map()</code> applies the function in the second argument to <strong>each</strong> element of the vector or list in the first argument. For example, consider applying the <code>get_sum_squares</code> function we wrote earlier to a list of vectors:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>num_list <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">vec1 =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">5</span>), <span class="at">vec2 =</span> <span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">8</span>, <span class="dv">3</span>, <span class="dv">5</span>), <span class="at">vec3 =</span> <span class="dv">1</span>)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">map</span>(num_list, get_sum_squares)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$vec1
[1] 42

$vec2
[1] 179

$vec3
[1] 1</code></pre>
</div>
</div>
<p>The output is a list of sums of squares calculated with our <code>get_sum_squares()</code> function.</p>
<p>To apply the <code>map()</code> approach to iteration to our baseball web urls, we will create an object called <code>url_vec</code> that has the urls of each school.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>url_vec <span class="ot">&lt;-</span> school_df<span class="sc">$</span>hitting_web_url</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, we apply <code>map()</code> with the first argument being the <code>url_vec</code> and the second argument being the function <code>get_hitting_data()</code> that we wrote earlier.</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>hitting_list <span class="ot">&lt;-</span> <span class="fu">map</span>(url_vec, get_hitting_data)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>hitting_list</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Scraping and performing the <code>wOBA</code> calculation will take a few seconds. The output is a list of 10 tibbles. The <code>bind_rows()</code> function that we used to stack rows of different data frames or tibbles can also be used to stack rows of data frames or tibbles given in a list. We apply the function to the scraped data and then add the name of the school to the data frame with a <code>left_join()</code>:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>hitting_ll <span class="ot">&lt;-</span> hitting_list <span class="sc">|&gt;</span> <span class="fu">bind_rows</span>() <span class="sc">|&gt;</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(school_df, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"url_name"</span> <span class="ot">=</span> <span class="st">"hitting_web_url"</span>))</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>hitting_ll</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 213 × 25
     `#` Player      AVG   OPS `GP-GS`    AB     R     H  `2B`  `3B`    HR   RBI
   &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
 1     6 "Clark, … 0.367 1.02  29-19      79    24    29     5     2     3    23
 2    19 "Delaney… 0.33  0.817 34-34     115    18    38     5     1     1    24
 3    13 "Butler,… 0.325 1.08  35-35     126    31    41     9     5     7    36
 4    30 "Watson,… 0.318 0.853 35-33     110    29    35     6     0     1    20
 5     5 "Desjard… 0.284 0.741 28-20      67    23    19     1     0     0     9
 6    20 "Courtwr… 0.281 0.646 27-17      64     6    18     2     0     0    13
 7    37 "Goretti… 0.268 0.771 32-32      97    18    26     6     3     0    14
 8    11 "Circell… 0.252 1.00  35-33     111    27    28     9     0    11    35
 9     8 "Forgion… 0.244 0.799 27-27      86    22    21     4     0     4    17
10    41 "Comerfo… 0.222 0.582 31-21      72    16    16     0     0     0     6
# … with 203 more rows, and 13 more variables: TB &lt;int&gt;, `SLG%` &lt;dbl&gt;,
#   BB &lt;int&gt;, HBP &lt;int&gt;, SO &lt;int&gt;, GDP &lt;int&gt;, `OB%` &lt;dbl&gt;, SF &lt;int&gt;, SH &lt;int&gt;,
#   `SB-ATT` &lt;chr&gt;, wOBA &lt;dbl&gt;, url_name &lt;chr&gt;, school_name &lt;chr&gt;</code></pre>
</div>
</div>
<p>With this data set, we can now do things like figure out the top 3 hitters from each team, according to the <code>wOBA</code> metric:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>hitting_ll <span class="sc">|&gt;</span> <span class="fu">group_by</span>(school_name) <span class="sc">|&gt;</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(wOBA)) <span class="sc">|&gt;</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) <span class="sc">|&gt;</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Player, school_name, wOBA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 3
# Groups:   school_name [10]
   Player                                                          schoo…¹  wOBA
   &lt;chr&gt;                                                           &lt;chr&gt;   &lt;dbl&gt;
 1 "Toby, Jared\r\n                                              … Bard    0.488
 2 "Dumper, Sam\r\n                                              … Bard    0.475
 3 "Myers, Jordan\r\n                                            … Bard    0.431
 4 "Cantor, Danny\r\n                                            … Clarks… 0.805
 5 "Price, Grant\r\n                                             … Clarks… 0.475
 6 "Doyle, Caleb\r\n                                             … Clarks… 0.473
 7 "Shirley, Buzz\r\n                                            … Ithaca  0.524
 8 "Fabbo, Louis\r\n                                             … Ithaca  0.465
 9 "Fabian, Matt\r\n                                             … Ithaca  0.428
10 "Blackall, Patrick \r\n                                       … RIT     0.399
# … with 20 more rows, and abbreviated variable name ¹​school_name</code></pre>
</div>
</div>
<p>or find the players on each team with the most at bats <code>AB</code>:</p>
<div class="cell" data-appendix="true">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>hitting_ll <span class="sc">|&gt;</span> <span class="fu">group_by</span>(school_name) <span class="sc">|&gt;</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(AB)) <span class="sc">|&gt;</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) <span class="sc">|&gt;</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Player, school_name, AB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 3
# Groups:   school_name [10]
   Player                                                          schoo…¹    AB
   &lt;chr&gt;                                                           &lt;chr&gt;   &lt;int&gt;
 1 "Toby, Jared\r\n                                              … Bard      107
 2 "Myers, Jordan\r\n                                            … Bard      107
 3 "Luscher, Alex\r\n                                            … Bard      101
 4 "Brouillette, Colby\r\n                                       … Clarks…   127
 5 "Wilson, Kent\r\n                                             … Clarks…   126
 6 "Doyle, Caleb\r\n                                             … Clarks…   103
 7 "Pedersen, Connor\r\n                                         … Ithaca    207
 8 "Cutaia, Nicholas\r\n                                         … Ithaca    180
 9 "Merod, Gil\r\n                                               … Ithaca    169
10 "Reilly, Chris\r\n                                            … RIT       152
# … with 20 more rows, and abbreviated variable name ¹​school_name</code></pre>
</div>
</div>
</section>
<section id="exercise-15-3" class="level3" data-number="15.3.3">
<h3 data-number="15.3.3" class="anchored" data-anchor-id="exercise-15-3"><span class="header-section-number">15.3.3</span> Exercises</h3>
<p>Exercises marked with an * indicate that the exercise has a solution at the end of the chapter at @ref(solutions-15).</p>
<p>The code below scrapes data from a wikipedia page listing the billboard end of year “hot 100” songs for the year 2021</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rvest)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>year_scrape <span class="ot">&lt;-</span> <span class="dv">2021</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_"</span>, year_scrape)</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a><span class="do">## convert the html code into something R can read</span></span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>billboard_tab <span class="ot">&lt;-</span> <span class="fu">read_html</span>(url) <span class="sc">|&gt;</span> <span class="fu">html_nodes</span>(<span class="st">"table"</span>)</span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-10"><a href="#cb92-10" aria-hidden="true" tabindex="-1"></a><span class="do">## grabs the tables</span></span>
<span id="cb92-11"><a href="#cb92-11" aria-hidden="true" tabindex="-1"></a>billboard_df <span class="ot">&lt;-</span> billboard_tab[[<span class="dv">1</span>]] <span class="sc">|&gt;</span> <span class="fu">html_table</span>() <span class="sc">|&gt;</span></span>
<span id="cb92-12"><a href="#cb92-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> year_scrape)</span>
<span id="cb92-13"><a href="#cb92-13" aria-hidden="true" tabindex="-1"></a>billboard_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 100 × 4
     No. Title                                `Artist(s)`                   year
   &lt;int&gt; &lt;chr&gt;                                &lt;chr&gt;                        &lt;dbl&gt;
 1     1 "\"Levitating\""                     Dua Lipa                      2021
 2     2 "\"Save Your Tears\""                The Weeknd and Ariana Grande  2021
 3     3 "\"Blinding Lights\""                The Weeknd                    2021
 4     4 "\"Mood\""                           24kGoldn featuring Iann Dior  2021
 5     5 "\"Good 4 U\""                       Olivia Rodrigo                2021
 6     6 "\"Kiss Me More\""                   Doja Cat featuring SZA        2021
 7     7 "\"Leave the Door Open\""            Silk Sonic (Bruno Mars and …  2021
 8     8 "\"Drivers License\""                Olivia Rodrigo                2021
 9     9 "\"Montero (Call Me by Your Name)\"" Lil Nas X                     2021
10    10 "\"Peaches\""                        Justin Bieber featuring Dan…  2021
# … with 90 more rows</code></pre>
</div>
</div>
<ol type="1">
<li><p>Wrap the code above in a function that scrapes data from Wikipedia for a user-provided <code>year_scrape</code> argument.</p></li>
<li><p>Create either a vector of the years 2014 through 2021 or a list of the years 2014 through 2021. Use your vector or list, along with the function you wrote in Exercise 1 and the <code>map()</code> function, to scrape data tables from each year.</p></li>
<li><p>Combine the data frames you scraped in Exercise 2 with <code>bind_rows()</code> and use the combined data set to figure out which artist appears the highest number of times in the billboard hot 100 list within the years 2014 through 2021. To save time, once you have the data frames combined you should be able to do something like:</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>combined_df <span class="sc">|&gt;</span> <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Artist(s)</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n_appear =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n_appear))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="4" type="1">
<li><p>* Note that your solution to Exercise 3 is likely imperfect because of songs that feature another musical artist. Why would such songs present a problem in counting the number of songs for each artist?</p></li>
<li><p>Write a short, one paragraph summary on your major take-aways from this section.</p></li>
</ol>
</section>
</section>
<section id="chapexercise-15" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="chapexercise-15"><span class="header-section-number">15.4</span> Chapter Exercises</h2>
<p>There are no chapter exercises for this section on connections to STAT 113, STAT 213, and CS 140.</p>
</section>
<section id="solutions-15" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="solutions-15"><span class="header-section-number">15.5</span> Exercise Solutions</h2>
<section id="stat-113-s" class="level3" data-number="15.5.1">
<h3 data-number="15.5.1" class="anchored" data-anchor-id="stat-113-s"><span class="header-section-number">15.5.1</span> STAT 113 S</h3>
</section>
<section id="stat-213-s" class="level3" data-number="15.5.2">
<h3 data-number="15.5.2" class="anchored" data-anchor-id="stat-213-s"><span class="header-section-number">15.5.2</span> STAT 213 S</h3>
</section>
<section id="cs-140-s" class="level3" data-number="15.5.3">
<h3 data-number="15.5.3" class="anchored" data-anchor-id="cs-140-s"><span class="header-section-number">15.5.3</span> CS 140 S</h3>
<ol start="4" type="1">
<li>* Note that your solution to Exercise 3 is likely imperfect because of songs that feature another musical artist. Why would such songs present a problem in counting the number of songs for each artist?</li>
</ol>
<p>When we <code>group_by()</code> musical artist and use our counting function <code>n()</code>, the artist by themselves and the artist featuring the other musician would be counted separately in our table.</p>
</section>
</section>
<section id="rcode-15" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="rcode-15"><span class="header-section-number">15.6</span> Non-Exercise <code>R</code> Code</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(openintro)</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>resume</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>resume_sum <span class="ot">&lt;-</span> resume <span class="sc">|&gt;</span> </span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">received_callback =</span> received_callback) <span class="sc">|&gt;</span></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>           <span class="fu">group_by</span>(race, received_callback) <span class="sc">|&gt;</span></span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resume_sum, <span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> count)) <span class="sc">+</span></span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">fill =</span> received_callback)) <span class="sc">+</span></span>
<span id="cb95-10"><a href="#cb95-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>()</span>
<span id="cb95-11"><a href="#cb95-11" aria-hidden="true" tabindex="-1"></a>resume <span class="ot">&lt;-</span> resume <span class="sc">|&gt;</span></span>
<span id="cb95-12"><a href="#cb95-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">received_callback =</span> <span class="fu">as.factor</span>(received_callback))</span>
<span id="cb95-13"><a href="#cb95-13" aria-hidden="true" tabindex="-1"></a>resume_sum <span class="ot">&lt;-</span> resume <span class="sc">|&gt;</span> </span>
<span id="cb95-14"><a href="#cb95-14" aria-hidden="true" tabindex="-1"></a>           <span class="fu">group_by</span>(race, received_callback) <span class="sc">|&gt;</span></span>
<span id="cb95-15"><a href="#cb95-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb95-16"><a href="#cb95-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resume_sum, <span class="fu">aes</span>(<span class="at">x =</span> race, <span class="at">y =</span> count)) <span class="sc">+</span></span>
<span id="cb95-17"><a href="#cb95-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">fill =</span> received_callback)) <span class="sc">+</span></span>
<span id="cb95-18"><a href="#cb95-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>()</span>
<span id="cb95-19"><a href="#cb95-19" aria-hidden="true" tabindex="-1"></a>resume <span class="sc">|&gt;</span> <span class="fu">group_by</span>(race, received_callback) <span class="sc">|&gt;</span></span>
<span id="cb95-20"><a href="#cb95-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb95-21"><a href="#cb95-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> race,</span>
<span id="cb95-22"><a href="#cb95-22" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> count)</span>
<span id="cb95-23"><a href="#cb95-23" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="at">x =</span> resume<span class="sc">$</span>race, <span class="at">y =</span> resume<span class="sc">$</span>received_callback)</span>
<span id="cb95-24"><a href="#cb95-24" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resume, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(<span class="fu">fct_infreq</span>(job_type)))) <span class="sc">+</span></span>
<span id="cb95-25"><a href="#cb95-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb95-26"><a href="#cb95-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb95-27"><a href="#cb95-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Job Type"</span>)</span>
<span id="cb95-28"><a href="#cb95-28" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resume, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(<span class="fu">fct_infreq</span>(job_industry)))) <span class="sc">+</span></span>
<span id="cb95-29"><a href="#cb95-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb95-30"><a href="#cb95-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb95-31"><a href="#cb95-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Job Industry"</span>)</span>
<span id="cb95-32"><a href="#cb95-32" aria-hidden="true" tabindex="-1"></a>resume_firstname <span class="ot">&lt;-</span> resume <span class="sc">|&gt;</span></span>
<span id="cb95-33"><a href="#cb95-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(firstname) <span class="sc">|&gt;</span></span>
<span id="cb95-34"><a href="#cb95-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">propcallback =</span> <span class="fu">mean</span>(received_callback <span class="sc">==</span> <span class="st">"1"</span>),</span>
<span id="cb95-35"><a href="#cb95-35" aria-hidden="true" tabindex="-1"></a>            <span class="at">gender =</span> <span class="fu">unique</span>(gender),</span>
<span id="cb95-36"><a href="#cb95-36" aria-hidden="true" tabindex="-1"></a>            <span class="at">race =</span> <span class="fu">unique</span>(race)) <span class="sc">|&gt;</span></span>
<span id="cb95-37"><a href="#cb95-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(propcallback)) <span class="sc">|&gt;</span></span>
<span id="cb95-38"><a href="#cb95-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unite</span>(<span class="st">"gender_race"</span>, <span class="fu">c</span>(gender, race))</span>
<span id="cb95-39"><a href="#cb95-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-40"><a href="#cb95-40" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resume_firstname, <span class="fu">aes</span>(<span class="at">x =</span> gender_race, <span class="at">y =</span> propcallback)) <span class="sc">+</span></span>
<span id="cb95-41"><a href="#cb95-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span>
<span id="cb95-42"><a href="#cb95-42" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb95-43"><a href="#cb95-43" aria-hidden="true" tabindex="-1"></a>label_df <span class="ot">&lt;-</span> resume_firstname <span class="sc">|&gt;</span> </span>
<span id="cb95-44"><a href="#cb95-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(propcallback <span class="sc">==</span> <span class="fu">max</span>(propcallback) <span class="sc">|</span></span>
<span id="cb95-45"><a href="#cb95-45" aria-hidden="true" tabindex="-1"></a>           propcallback <span class="sc">==</span> <span class="fu">min</span>(propcallback))</span>
<span id="cb95-46"><a href="#cb95-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-47"><a href="#cb95-47" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resume_firstname, <span class="fu">aes</span>(<span class="at">x =</span> gender_race, <span class="at">y =</span> propcallback)) <span class="sc">+</span></span>
<span id="cb95-48"><a href="#cb95-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb95-49"><a href="#cb95-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_label_repel</span>(<span class="at">data =</span> label_df, <span class="fu">aes</span>(<span class="at">label =</span> firstname))</span>
<span id="cb95-50"><a href="#cb95-50" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb95-51"><a href="#cb95-51" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb95-52"><a href="#cb95-52" aria-hidden="true" tabindex="-1"></a>coffee_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data/coffee_ratings.csv"</span>))</span>
<span id="cb95-53"><a href="#cb95-53" aria-hidden="true" tabindex="-1"></a>coffee_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(total_cup_points <span class="sc">~</span> species <span class="sc">+</span> aroma <span class="sc">+</span> flavor <span class="sc">+</span></span>
<span id="cb95-54"><a href="#cb95-54" aria-hidden="true" tabindex="-1"></a>                   sweetness <span class="sc">+</span> moisture,</span>
<span id="cb95-55"><a href="#cb95-55" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> coffee_df)</span>
<span id="cb95-56"><a href="#cb95-56" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(coffee_mod)</span>
<span id="cb95-57"><a href="#cb95-57" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(coffee_mod)<span class="sc">$</span>coefficients[<span class="st">"moisture"</span>, <span class="dv">4</span>]</span>
<span id="cb95-58"><a href="#cb95-58" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(coffee_mod)</span>
<span id="cb95-59"><a href="#cb95-59" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(coffee_mod) <span class="sc">|&gt;</span> <span class="fu">select</span>(p.value)</span>
<span id="cb95-60"><a href="#cb95-60" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(coffee_mod) <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"aroma"</span>)</span>
<span id="cb95-61"><a href="#cb95-61" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(coffee_mod)</span>
<span id="cb95-62"><a href="#cb95-62" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(coffee_mod)</span>
<span id="cb95-63"><a href="#cb95-63" aria-hidden="true" tabindex="-1"></a>augment_df <span class="ot">&lt;-</span> <span class="fu">augment</span>(coffee_mod)</span>
<span id="cb95-64"><a href="#cb95-64" aria-hidden="true" tabindex="-1"></a>augment_df <span class="sc">|&gt;</span> <span class="fu">filter</span>(.cooksd <span class="sc">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb95-65"><a href="#cb95-65" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> coffee_df, <span class="fu">aes</span>(<span class="at">x =</span> total_cup_points)) <span class="sc">+</span></span>
<span id="cb95-66"><a href="#cb95-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">15</span>, <span class="at">fill =</span> <span class="st">"white"</span>, <span class="at">colour =</span> <span class="st">"black"</span>)</span>
<span id="cb95-67"><a href="#cb95-67" aria-hidden="true" tabindex="-1"></a>augment_df <span class="sc">|&gt;</span> <span class="fu">filter</span>(.hat <span class="sc">&gt;</span> <span class="fl">0.2</span>)</span>
<span id="cb95-68"><a href="#cb95-68" aria-hidden="true" tabindex="-1"></a>augment_df <span class="sc">|&gt;</span> <span class="fu">filter</span>(.std.resid <span class="sc">&gt;</span> <span class="dv">3</span> <span class="sc">|</span> .std.resid <span class="sc">&lt;</span> <span class="sc">-</span><span class="dv">3</span>)</span>
<span id="cb95-69"><a href="#cb95-69" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> augment_df <span class="sc">|&gt;</span> <span class="fu">filter</span>(.fitted <span class="sc">&gt;</span> <span class="dv">25</span>), <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb95-70"><a href="#cb95-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() </span>
<span id="cb95-71"><a href="#cb95-71" aria-hidden="true" tabindex="-1"></a>coffee_noout <span class="ot">&lt;-</span> coffee_df <span class="sc">|&gt;</span> <span class="fu">filter</span>(total_cup_points <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb95-72"><a href="#cb95-72" aria-hidden="true" tabindex="-1"></a>coffee_fa <span class="ot">&lt;-</span> <span class="fu">lm</span>(total_cup_points <span class="sc">~</span> flavor <span class="sc">+</span> aroma,</span>
<span id="cb95-73"><a href="#cb95-73" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> coffee_noout)</span>
<span id="cb95-74"><a href="#cb95-74" aria-hidden="true" tabindex="-1"></a>coffee_fa <span class="sc">|&gt;</span> <span class="fu">tidy</span>()</span>
<span id="cb95-75"><a href="#cb95-75" aria-hidden="true" tabindex="-1"></a><span class="do">## install.packages("modelr")</span></span>
<span id="cb95-76"><a href="#cb95-76" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelr)</span>
<span id="cb95-77"><a href="#cb95-77" aria-hidden="true" tabindex="-1"></a>grid_vals <span class="ot">&lt;-</span> coffee_noout <span class="sc">|&gt;</span></span>
<span id="cb95-78"><a href="#cb95-78" aria-hidden="true" tabindex="-1"></a>  modelr<span class="sc">::</span><span class="fu">data_grid</span>(</span>
<span id="cb95-79"><a href="#cb95-79" aria-hidden="true" tabindex="-1"></a>    <span class="at">flavor =</span> <span class="fu">quantile</span>(flavor),</span>
<span id="cb95-80"><a href="#cb95-80" aria-hidden="true" tabindex="-1"></a>    <span class="at">aroma =</span> <span class="fu">quantile</span>(aroma)</span>
<span id="cb95-81"><a href="#cb95-81" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb95-82"><a href="#cb95-82" aria-hidden="true" tabindex="-1"></a>grid_vals</span>
<span id="cb95-83"><a href="#cb95-83" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> grid_vals <span class="sc">|&gt;</span></span>
<span id="cb95-84"><a href="#cb95-84" aria-hidden="true" tabindex="-1"></a>  modelr<span class="sc">::</span><span class="fu">gather_predictions</span>(coffee_fa)</span>
<span id="cb95-85"><a href="#cb95-85" aria-hidden="true" tabindex="-1"></a>grid</span>
<span id="cb95-86"><a href="#cb95-86" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> coffee_noout, <span class="fu">aes</span>(<span class="at">x =</span> flavor, <span class="at">y =</span> total_cup_points)) <span class="sc">+</span></span>
<span id="cb95-87"><a href="#cb95-87" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb95-88"><a href="#cb95-88" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> grid, <span class="fu">aes</span>(<span class="at">colour =</span> <span class="fu">fct_rev</span>(<span class="fu">factor</span>(aroma)),</span>
<span id="cb95-89"><a href="#cb95-89" aria-hidden="true" tabindex="-1"></a>                             <span class="at">y =</span> pred), <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb95-90"><a href="#cb95-90" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb95-91"><a href="#cb95-91" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">"Aroma"</span>) <span class="sc">+</span></span>
<span id="cb95-92"><a href="#cb95-92" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb95-93"><a href="#cb95-93" aria-hidden="true" tabindex="-1"></a>coffee_fa_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(total_cup_points <span class="sc">~</span> flavor <span class="sc">+</span> aroma <span class="sc">+</span> flavor<span class="sc">:</span>aroma,</span>
<span id="cb95-94"><a href="#cb95-94" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> coffee_noout)</span>
<span id="cb95-95"><a href="#cb95-95" aria-hidden="true" tabindex="-1"></a>coffee_fa_int <span class="sc">|&gt;</span> <span class="fu">tidy</span>()</span>
<span id="cb95-96"><a href="#cb95-96" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> coffee_noout <span class="sc">|&gt;</span></span>
<span id="cb95-97"><a href="#cb95-97" aria-hidden="true" tabindex="-1"></a>  modelr<span class="sc">::</span><span class="fu">data_grid</span>(</span>
<span id="cb95-98"><a href="#cb95-98" aria-hidden="true" tabindex="-1"></a>    <span class="at">flavor =</span> <span class="fu">quantile</span>(flavor),</span>
<span id="cb95-99"><a href="#cb95-99" aria-hidden="true" tabindex="-1"></a>    <span class="at">aroma =</span> <span class="fu">quantile</span>(aroma), </span>
<span id="cb95-100"><a href="#cb95-100" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb95-101"><a href="#cb95-101" aria-hidden="true" tabindex="-1"></a>  modelr<span class="sc">::</span><span class="fu">gather_predictions</span>(coffee_fa_int)</span>
<span id="cb95-102"><a href="#cb95-102" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> coffee_noout, <span class="fu">aes</span>(<span class="at">x =</span> flavor, <span class="at">y =</span> total_cup_points)) <span class="sc">+</span></span>
<span id="cb95-103"><a href="#cb95-103" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb95-104"><a href="#cb95-104" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> grid, <span class="fu">aes</span>(<span class="at">colour =</span> <span class="fu">fct_rev</span>(<span class="fu">factor</span>(aroma)), <span class="at">y =</span> pred), <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb95-105"><a href="#cb95-105" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb95-106"><a href="#cb95-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">"Aroma"</span>) <span class="sc">+</span></span>
<span id="cb95-107"><a href="#cb95-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb95-108"><a href="#cb95-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-109"><a href="#cb95-109" aria-hidden="true" tabindex="-1"></a><span class="co"># grid &lt;- coffee_noout |&gt;</span></span>
<span id="cb95-110"><a href="#cb95-110" aria-hidden="true" tabindex="-1"></a><span class="co">#   modelr::data_grid(</span></span>
<span id="cb95-111"><a href="#cb95-111" aria-hidden="true" tabindex="-1"></a><span class="co">#     flavor = quantile(aroma),</span></span>
<span id="cb95-112"><a href="#cb95-112" aria-hidden="true" tabindex="-1"></a><span class="co">#     aroma = quantile(flavor), </span></span>
<span id="cb95-113"><a href="#cb95-113" aria-hidden="true" tabindex="-1"></a><span class="co">#   ) |&gt;</span></span>
<span id="cb95-114"><a href="#cb95-114" aria-hidden="true" tabindex="-1"></a><span class="co">#   modelr::gather_predictions(coffee_fa_int)</span></span>
<span id="cb95-115"><a href="#cb95-115" aria-hidden="true" tabindex="-1"></a><span class="co"># coffee_noout &lt;- coffee_noout |&gt; mutate(flavor_cut = cut(flavor, breaks = 5))</span></span>
<span id="cb95-116"><a href="#cb95-116" aria-hidden="true" tabindex="-1"></a><span class="co"># ggplot(data = coffee_noout, aes(x = aroma, y = total_cup_points)) +</span></span>
<span id="cb95-117"><a href="#cb95-117" aria-hidden="true" tabindex="-1"></a><span class="co">#   geom_point(alpha = 0.2, aes(colour = flavor_cut)) +</span></span>
<span id="cb95-118"><a href="#cb95-118" aria-hidden="true" tabindex="-1"></a><span class="co">#   geom_smooth(aes(colour = flavor_cut), method = "lm", fullrange = TRUE, se = FALSE) +</span></span>
<span id="cb95-119"><a href="#cb95-119" aria-hidden="true" tabindex="-1"></a><span class="co">#   scale_colour_viridis_d() +</span></span>
<span id="cb95-120"><a href="#cb95-120" aria-hidden="true" tabindex="-1"></a><span class="co">#   theme_minimal()</span></span>
<span id="cb95-121"><a href="#cb95-121" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb95-122"><a href="#cb95-122" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rvest)</span>
<span id="cb95-123"><a href="#cb95-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-124"><a href="#cb95-124" aria-hidden="true" tabindex="-1"></a>url_SLU <span class="ot">&lt;-</span> <span class="st">"https://saintsathletics.com/sports/baseball/stats/2022"</span></span>
<span id="cb95-125"><a href="#cb95-125" aria-hidden="true" tabindex="-1"></a>tab_SLU <span class="ot">&lt;-</span> <span class="fu">read_html</span>(url_SLU) <span class="sc">|&gt;</span> <span class="fu">html_nodes</span>(<span class="st">"table"</span>)</span>
<span id="cb95-126"><a href="#cb95-126" aria-hidden="true" tabindex="-1"></a>SLU_Hitting <span class="ot">&lt;-</span> tab_SLU[[<span class="dv">1</span>]] <span class="sc">|&gt;</span> <span class="fu">html_table</span>(<span class="at">fill =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb95-127"><a href="#cb95-127" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="sc">-</span><span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb95-128"><a href="#cb95-128" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="dv">23</span>) <span class="sc">|&gt;</span></span>
<span id="cb95-129"><a href="#cb95-129" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">wOBA =</span> (<span class="fl">0.69</span> <span class="sc">*</span> BB <span class="sc">+</span> <span class="fl">0.72</span> <span class="sc">*</span> HBP <span class="sc">+</span> <span class="fl">0.89</span> <span class="sc">*</span> (H<span class="sc">-</span><span class="st">`</span><span class="at">2B</span><span class="st">`</span><span class="sc">-</span><span class="st">`</span><span class="at">3B</span><span class="st">`</span><span class="sc">-</span><span class="st">`</span><span class="at">HR</span><span class="st">`</span>) <span class="sc">+</span> <span class="fl">1.27</span> <span class="sc">*</span> <span class="st">`</span><span class="at">2B</span><span class="st">`</span> <span class="sc">+</span> <span class="fl">1.62</span> <span class="sc">*</span> <span class="st">`</span><span class="at">3B</span><span class="st">`</span> <span class="sc">+</span> <span class="fl">2.10</span> <span class="sc">*</span> HR) <span class="sc">/</span> (AB <span class="sc">+</span> BB <span class="sc">+</span> SF <span class="sc">+</span> HBP))</span>
<span id="cb95-130"><a href="#cb95-130" aria-hidden="true" tabindex="-1"></a>SLU_Hitting <span class="sc">|&gt;</span> <span class="fu">select</span>(wOBA, <span class="fu">everything</span>()) <span class="sc">|&gt;</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(wOBA))</span>
<span id="cb95-131"><a href="#cb95-131" aria-hidden="true" tabindex="-1"></a>get_sum_squares <span class="ot">&lt;-</span> <span class="cf">function</span>(x_vec) {</span>
<span id="cb95-132"><a href="#cb95-132" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb95-133"><a href="#cb95-133" aria-hidden="true" tabindex="-1"></a>  sum_of_squares <span class="ot">&lt;-</span> <span class="fu">sum</span>(x_vec <span class="sc">^</span> <span class="dv">2</span>)</span>
<span id="cb95-134"><a href="#cb95-134" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb95-135"><a href="#cb95-135" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(sum_of_squares)</span>
<span id="cb95-136"><a href="#cb95-136" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb95-137"><a href="#cb95-137" aria-hidden="true" tabindex="-1"></a><span class="fu">get_sum_squares</span>(<span class="at">x_vec =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">1</span>))</span>
<span id="cb95-138"><a href="#cb95-138" aria-hidden="true" tabindex="-1"></a>get_hitting_data <span class="ot">&lt;-</span> <span class="cf">function</span>(url_name) {</span>
<span id="cb95-139"><a href="#cb95-139" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb95-140"><a href="#cb95-140" aria-hidden="true" tabindex="-1"></a>  tab <span class="ot">&lt;-</span> <span class="fu">read_html</span>(url_name) <span class="sc">|&gt;</span> <span class="fu">html_nodes</span>(<span class="st">"table"</span>)</span>
<span id="cb95-141"><a href="#cb95-141" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb95-142"><a href="#cb95-142" aria-hidden="true" tabindex="-1"></a>  hitting <span class="ot">&lt;-</span> tab[[<span class="dv">1</span>]] <span class="sc">|&gt;</span> <span class="fu">html_table</span>(<span class="at">fill =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb95-143"><a href="#cb95-143" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="sc">-</span><span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb95-144"><a href="#cb95-144" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span><span class="dv">23</span>) <span class="sc">|&gt;</span></span>
<span id="cb95-145"><a href="#cb95-145" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">wOBA =</span> (<span class="fl">0.69</span> <span class="sc">*</span> BB <span class="sc">+</span> <span class="fl">0.72</span> <span class="sc">*</span> HBP <span class="sc">+</span> <span class="fl">0.89</span> <span class="sc">*</span></span>
<span id="cb95-146"><a href="#cb95-146" aria-hidden="true" tabindex="-1"></a>                     (H<span class="sc">-</span> <span class="st">`</span><span class="at">2B</span><span class="st">`</span> <span class="sc">-</span> <span class="st">`</span><span class="at">3B</span><span class="st">`</span> <span class="sc">-</span> <span class="st">`</span><span class="at">HR</span><span class="st">`</span>) <span class="sc">+</span></span>
<span id="cb95-147"><a href="#cb95-147" aria-hidden="true" tabindex="-1"></a>                     <span class="fl">1.27</span> <span class="sc">*</span> <span class="st">`</span><span class="at">2B</span><span class="st">`</span> <span class="sc">+</span> <span class="fl">1.62</span> <span class="sc">*</span> <span class="st">`</span><span class="at">3B</span><span class="st">`</span> <span class="sc">+</span> <span class="fl">2.10</span> <span class="sc">*</span> HR) <span class="sc">/</span> </span>
<span id="cb95-148"><a href="#cb95-148" aria-hidden="true" tabindex="-1"></a>             (AB <span class="sc">+</span> BB <span class="sc">+</span> SF <span class="sc">+</span> HBP),</span>
<span id="cb95-149"><a href="#cb95-149" aria-hidden="true" tabindex="-1"></a>           <span class="at">url_name =</span> url_name)</span>
<span id="cb95-150"><a href="#cb95-150" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb95-151"><a href="#cb95-151" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(hitting)</span>
<span id="cb95-152"><a href="#cb95-152" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb95-153"><a href="#cb95-153" aria-hidden="true" tabindex="-1"></a><span class="fu">get_hitting_data</span>(<span class="at">url_name =</span> <span class="st">"https://saintsathletics.com/sports/baseball/stats/2022"</span>)</span>
<span id="cb95-154"><a href="#cb95-154" aria-hidden="true" tabindex="-1"></a>school_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">school_name =</span> <span class="fu">c</span>(<span class="st">"SLU"</span>, <span class="st">"Clarkson"</span>, <span class="st">"Rochester"</span>, <span class="st">"RIT"</span>, <span class="st">"Ithaca"</span>, <span class="st">"Skidmore"</span>, <span class="st">"RPI"</span>, <span class="st">"Union"</span>, <span class="st">"Bard"</span>, <span class="st">"Vassar"</span>),</span>
<span id="cb95-155"><a href="#cb95-155" aria-hidden="true" tabindex="-1"></a>                    <span class="at">hitting_web_url =</span> <span class="fu">c</span>(<span class="st">"https://saintsathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb95-156"><a href="#cb95-156" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://clarksonathletics.com/sports/baseball/stats/2022"</span>, </span>
<span id="cb95-157"><a href="#cb95-157" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://uofrathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb95-158"><a href="#cb95-158" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://ritathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb95-159"><a href="#cb95-159" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://athletics.ithaca.edu/sports/baseball/stats/2022"</span>,</span>
<span id="cb95-160"><a href="#cb95-160" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://skidmoreathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb95-161"><a href="#cb95-161" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://rpiathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb95-162"><a href="#cb95-162" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://unionathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb95-163"><a href="#cb95-163" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://bardathletics.com/sports/baseball/stats/2022"</span>,</span>
<span id="cb95-164"><a href="#cb95-164" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"https://www.vassarathletics.com/sports/baseball/stats/2022"</span>))</span>
<span id="cb95-165"><a href="#cb95-165" aria-hidden="true" tabindex="-1"></a>school_df</span>
<span id="cb95-166"><a href="#cb95-166" aria-hidden="true" tabindex="-1"></a><span class="fu">get_hitting_data</span>(<span class="at">url_name =</span> <span class="st">"https://saintsathletics.com/sports/baseball/stats/2022"</span>)</span>
<span id="cb95-167"><a href="#cb95-167" aria-hidden="true" tabindex="-1"></a><span class="fu">get_hitting_data</span>(<span class="at">url_name =</span> <span class="st">"https://clarksonathletics.com/sports/baseball/stats/2022"</span>)</span>
<span id="cb95-168"><a href="#cb95-168" aria-hidden="true" tabindex="-1"></a><span class="fu">get_hitting_data</span>(<span class="at">url_name =</span> <span class="st">"https://uofrathletics.com/sports/baseball/stats/2022"</span>)</span>
<span id="cb95-169"><a href="#cb95-169" aria-hidden="true" tabindex="-1"></a>num_list <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">vec1 =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">5</span>), <span class="at">vec2 =</span> <span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">8</span>, <span class="dv">3</span>, <span class="dv">5</span>), <span class="at">vec3 =</span> <span class="dv">1</span>)</span>
<span id="cb95-170"><a href="#cb95-170" aria-hidden="true" tabindex="-1"></a><span class="fu">map</span>(num_list, get_sum_squares)</span>
<span id="cb95-171"><a href="#cb95-171" aria-hidden="true" tabindex="-1"></a>url_vec <span class="ot">&lt;-</span> school_df<span class="sc">$</span>hitting_web_url</span>
<span id="cb95-172"><a href="#cb95-172" aria-hidden="true" tabindex="-1"></a>hitting_list <span class="ot">&lt;-</span> <span class="fu">map</span>(url_vec, get_hitting_data)</span>
<span id="cb95-173"><a href="#cb95-173" aria-hidden="true" tabindex="-1"></a>hitting_list</span>
<span id="cb95-174"><a href="#cb95-174" aria-hidden="true" tabindex="-1"></a>hitting_ll <span class="ot">&lt;-</span> hitting_list <span class="sc">|&gt;</span> <span class="fu">bind_rows</span>() <span class="sc">|&gt;</span></span>
<span id="cb95-175"><a href="#cb95-175" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(school_df, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"url_name"</span> <span class="ot">=</span> <span class="st">"hitting_web_url"</span>))</span>
<span id="cb95-176"><a href="#cb95-176" aria-hidden="true" tabindex="-1"></a>hitting_ll</span>
<span id="cb95-177"><a href="#cb95-177" aria-hidden="true" tabindex="-1"></a>hitting_ll <span class="sc">|&gt;</span> <span class="fu">group_by</span>(school_name) <span class="sc">|&gt;</span></span>
<span id="cb95-178"><a href="#cb95-178" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(wOBA)) <span class="sc">|&gt;</span></span>
<span id="cb95-179"><a href="#cb95-179" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) <span class="sc">|&gt;</span></span>
<span id="cb95-180"><a href="#cb95-180" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Player, school_name, wOBA)</span>
<span id="cb95-181"><a href="#cb95-181" aria-hidden="true" tabindex="-1"></a>hitting_ll <span class="sc">|&gt;</span> <span class="fu">group_by</span>(school_name) <span class="sc">|&gt;</span></span>
<span id="cb95-182"><a href="#cb95-182" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(AB)) <span class="sc">|&gt;</span></span>
<span id="cb95-183"><a href="#cb95-183" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) <span class="sc">|&gt;</span></span>
<span id="cb95-184"><a href="#cb95-184" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Player, school_name, AB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./13-knn.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Predictive Modeling with knn</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./16-sql.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Introduction to SQL with <code>dbplyr</code></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Course Materials were written by Matt Higham for STAT/DATA 234 at St.&nbsp;Lawrence University.</div>   
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>